// <auto-generated />
// Generated by FCT Engineering Studio instrument center. Do not edit by hand.
namespace CSP
{
    public partial class TestDllMain
    {
        public void UI_CALIBRATIONCAN_ReceiveRaw(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "CALIBRATIONCAN", "ReceiveRaw");
        }

        public void UI_CALIBRATIONCAN_SendDbcSignal(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "CALIBRATIONCAN", "SendDbcSignal");
        }

        public void UI_CALIBRATIONCAN_SendRaw(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "CALIBRATIONCAN", "SendRaw");
        }

        public void UI_DAQ_Read(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "DAQ", "Read");
        }

        public void UI_DCDC_LOAD_ClearProtection(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "DCDC_LOAD", "ClearProtection");
        }

        public void UI_DCDC_LOAD_OutputOff(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "DCDC_LOAD", "OutputOff");
        }

        public void UI_DCDC_LOAD_OutputOn(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "DCDC_LOAD", "OutputOn");
        }

        public void UI_DCDC_LOAD_ReadCurrent(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "DCDC_LOAD", "ReadCurrent");
        }

        public void UI_DCDC_LOAD_ReadPower(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "DCDC_LOAD", "ReadPower");
        }

        public void UI_DCDC_LOAD_ReadProtection(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "DCDC_LOAD", "ReadProtection");
        }

        public void UI_DCDC_LOAD_ReadVoltage(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "DCDC_LOAD", "ReadVoltage");
        }

        public void UI_DCDC_LOAD_Reset(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "DCDC_LOAD", "Reset");
        }

        public void UI_DCDC_LOAD_SetCurrent(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "DCDC_LOAD", "SetCurrent");
        }

        public void UI_DCDC_LOAD_SetMode(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "DCDC_LOAD", "SetMode");
        }

        public void UI_DCDC_LOAD_SetPower(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "DCDC_LOAD", "SetPower");
        }

        public void UI_DCDC_LOAD_SetResistance(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "DCDC_LOAD", "SetResistance");
        }

        public void UI_DCDC_LOAD_SetVoltage(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "DCDC_LOAD", "SetVoltage");
        }

        public void UI_DMM_Close(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "DMM", "Close");
        }

        public void UI_DMM_ConfigACCurrent(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "DMM", "ConfigACCurrent");
        }

        public void UI_DMM_ConfigACVoltage(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "DMM", "ConfigACVoltage");
        }

        public void UI_DMM_ConfigCalculateMaximum(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "DMM", "ConfigCalculateMaximum");
        }

        public void UI_DMM_ConfigDCCurrent(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "DMM", "ConfigDCCurrent");
        }

        public void UI_DMM_ConfigDCVoltage(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "DMM", "ConfigDCVoltage");
        }

        public void UI_DMM_ConfigFrequency(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "DMM", "ConfigFrequency");
        }

        public void UI_DMM_ConfigMeasure(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "DMM", "ConfigMeasure");
        }

        public void UI_DMM_ConfigResistance(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "DMM", "ConfigResistance");
        }

        public void UI_DMM_HV_Close(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "DMM_HV", "Close");
        }

        public void UI_DMM_HV_ConfigACCurrent(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "DMM_HV", "ConfigACCurrent");
        }

        public void UI_DMM_HV_ConfigACVoltage(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "DMM_HV", "ConfigACVoltage");
        }

        public void UI_DMM_HV_ConfigCalculateMaximum(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "DMM_HV", "ConfigCalculateMaximum");
        }

        public void UI_DMM_HV_ConfigDCCurrent(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "DMM_HV", "ConfigDCCurrent");
        }

        public void UI_DMM_HV_ConfigDCVoltage(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "DMM_HV", "ConfigDCVoltage");
        }

        public void UI_DMM_HV_ConfigFrequency(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "DMM_HV", "ConfigFrequency");
        }

        public void UI_DMM_HV_ConfigMeasure(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "DMM_HV", "ConfigMeasure");
        }

        public void UI_DMM_HV_ConfigResistance(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "DMM_HV", "ConfigResistance");
        }

        public void UI_DMM_HV_Identify(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "DMM_HV", "Identify");
        }

        public void UI_DMM_HV_Init(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "DMM_HV", "Init");
        }

        public void UI_DMM_HV_Read(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "DMM_HV", "Read");
        }

        public void UI_DMM_HV_Reset(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "DMM_HV", "Reset");
        }

        public void UI_DMM_Identify(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "DMM", "Identify");
        }

        public void UI_DMM_Init(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "DMM", "Init");
        }

        public void UI_DMM_LV_Close(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "DMM_LV", "Close");
        }

        public void UI_DMM_LV_ConfigACCurrent(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "DMM_LV", "ConfigACCurrent");
        }

        public void UI_DMM_LV_ConfigACVoltage(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "DMM_LV", "ConfigACVoltage");
        }

        public void UI_DMM_LV_ConfigCalculateMaximum(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "DMM_LV", "ConfigCalculateMaximum");
        }

        public void UI_DMM_LV_ConfigDCCurrent(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "DMM_LV", "ConfigDCCurrent");
        }

        public void UI_DMM_LV_ConfigDCVoltage(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "DMM_LV", "ConfigDCVoltage");
        }

        public void UI_DMM_LV_ConfigFrequency(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "DMM_LV", "ConfigFrequency");
        }

        public void UI_DMM_LV_ConfigMeasure(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "DMM_LV", "ConfigMeasure");
        }

        public void UI_DMM_LV_ConfigResistance(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "DMM_LV", "ConfigResistance");
        }

        public void UI_DMM_LV_Identify(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "DMM_LV", "Identify");
        }

        public void UI_DMM_LV_Init(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "DMM_LV", "Init");
        }

        public void UI_DMM_LV_Read(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "DMM_LV", "Read");
        }

        public void UI_DMM_LV_Reset(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "DMM_LV", "Reset");
        }

        public void UI_DMM_Read(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "DMM", "Read");
        }

        public void UI_DMM_Reset(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "DMM", "Reset");
        }

        public void UI_HVDC_ReadCurrent(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "HVDC", "ReadCurrent");
        }

        public void UI_HVDC_ReadPower(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "HVDC", "ReadPower");
        }

        public void UI_HVDC_ReadVoltage(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "HVDC", "ReadVoltage");
        }

        public void UI_HVDC_SetCurrent(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "HVDC", "SetCurrent");
        }

        public void UI_HVDC_SetOutput(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "HVDC", "SetOutput");
        }

        public void UI_HVDC_SetPower(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "HVDC", "SetPower");
        }

        public void UI_HVDC_SetVoltage(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "HVDC", "SetVoltage");
        }

        public void UI_LVDC_KL15_ReadCurrent(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "LVDC_KL15", "ReadCurrent");
        }

        public void UI_LVDC_KL15_ReadVoltage(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "LVDC_KL15", "ReadVoltage");
        }

        public void UI_LVDC_KL15_SetCurrent(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "LVDC_KL15", "SetCurrent");
        }

        public void UI_LVDC_KL15_SetOutput(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "LVDC_KL15", "SetOutput");
        }

        public void UI_LVDC_KL15_SetVoltage(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "LVDC_KL15", "SetVoltage");
        }

        public void UI_LVDC_ReadCurrent(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "LVDC", "ReadCurrent");
        }

        public void UI_LVDC_ReadVoltage(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "LVDC", "ReadVoltage");
        }

        public void UI_LVDC_SetCurrent(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "LVDC", "SetCurrent");
        }

        public void UI_LVDC_SetOutput(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "LVDC", "SetOutput");
        }

        public void UI_LVDC_SetVoltage(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "LVDC", "SetVoltage");
        }

        public void UI_PLC_LoadFinished(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "PLC", "LoadFinished");
        }

        public void UI_RELAY_FCT_DisableFctMux(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "RELAY_FCT", "DisableFctMux");
        }

        public void UI_RELAY_FCT_SelectFctMux(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "RELAY_FCT", "SelectFctMux");
        }

        public void UI_RELAY_FCT_SetDO(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "RELAY_FCT", "SetDO");
        }

        public void UI_RELAY_HVMUX_Disable15(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "RELAY_HVMUX", "Disable15");
        }

        public void UI_RELAY_HVMUX_Select15(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "RELAY_HVMUX", "Select15");
        }

        public void UI_RELAY_HVMUX_SetDO(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "RELAY_HVMUX", "SetDO");
        }

        public void UI_RESOLVERCAN2_ReceiveRaw(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "RESOLVERCAN2", "ReceiveRaw");
        }

        public void UI_RESOLVERCAN2_SendDbcSignal(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "RESOLVERCAN2", "SendDbcSignal");
        }

        public void UI_RESOLVERCAN2_SendRaw(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "RESOLVERCAN2", "SendRaw");
        }

        public void UI_RES_1_SetResistance(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "RES_1", "SetResistance");
        }

        public void UI_RES_2_SetResistance(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "RES_2", "SetResistance");
        }

        public void UI_RES_3_SetResistance(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "RES_3", "SetResistance");
        }

        public void UI_RES_SetResistance(int socketIndex)
        {
            FCT_ExecuteConfiguredAction(socketIndex, "RES", "SetResistance");
        }

    }
}
