using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Effects;

namespace ManualCanDebug
{
    internal sealed class DbcSignalConfigurationWindow : Window
    {
        private readonly IList<DbcSignalEditRow> _sourceRows;
        private readonly ObservableCollection<DbcSignalEditRow> _rows;
        private readonly bool _readMode;
        private readonly ListCollectionView _view;
        private readonly DataGrid _grid;
        private readonly TextBox _search;
        private readonly TextBlock _footer;
        private readonly TextBox _stepName;
        private readonly Func<string, Task<string>> _run;
        private ToggleButton _allFilter;
        private ToggleButton _selectedFilter;
        private CheckBox _useHeader;
        private string _filter = "全部";
        private bool _guard;

        public string StepName { get { return _stepName == null ? string.Empty : _stepName.Text.Trim(); } }

        public DbcSignalConfigurationWindow(IEnumerable<DbcSignalEditRow> rows, string mode, string messageName, string stepName = null, Func<string, Task<string>> run = null)
        {
            _sourceRows = (rows ?? Enumerable.Empty<DbcSignalEditRow>()).ToList(); _rows = new ObservableCollection<DbcSignalEditRow>(_sourceRows.Select(value => value.CloneForEditing())); _readMode = string.Equals(mode, "读取DBC信号", StringComparison.Ordinal); _run = run;
            Title = "DBC信号配置"; Width = 1210; Height = 710; MinWidth = 1210; MinHeight = 710; WindowStartupLocation = WindowStartupLocation.CenterOwner; WindowStyle = WindowStyle.None; AllowsTransparency = true; ResizeMode = ResizeMode.NoResize; Background = Brushes.Transparent; FontFamily = new FontFamily("Microsoft YaHei UI"); FontSize = 13; StudioControlTheme.Apply(Resources);
            Border shell = new Border { Background = Brushes.White, BorderBrush = BorderColor(), BorderThickness = new Thickness(1), CornerRadius = new CornerRadius(8), Effect = new DropShadowEffect { BlurRadius = 18, ShadowDepth = 2, Opacity = 0.2, Color = Colors.SlateGray } };
            Grid root = new Grid(); root.RowDefinitions.Add(new RowDefinition { Height = new GridLength(58) }); root.RowDefinitions.Add(new RowDefinition { Height = new GridLength(62) }); root.RowDefinitions.Add(new RowDefinition { Height = new GridLength(1, GridUnitType.Star) }); root.RowDefinitions.Add(new RowDefinition { Height = new GridLength(64) });
            DockPanel header = new DockPanel { Background = Brushes.White }; header.MouseLeftButtonDown += (s, e) => { if (e.ButtonState == MouseButtonState.Pressed) DragMove(); }; Button close = new Button { Content = "×", Width = 48, Height = 40, Margin = new Thickness(0, 7, 7, 7), FontSize = 22, Foreground = Text(92, 105, 123), Background = Brushes.Transparent, BorderThickness = new Thickness(0), Cursor = Cursors.Hand }; close.Click += (s, e) => DialogResult = false; DockPanel.SetDock(close, Dock.Right); header.Children.Add(close); header.Children.Add(new TextBlock { Text = "DBC信号配置", FontSize = 18, FontWeight = FontWeights.SemiBold, Foreground = Text(32, 43, 59), VerticalAlignment = VerticalAlignment.Center, Margin = new Thickness(22, 0, 12, 0) }); root.Children.Add(header); Border actionHeader = new Border { Background = new SolidColorBrush(Color.FromRgb(248, 250, 253)), BorderBrush = BorderColor(), BorderThickness = new Thickness(0, 1, 0, 1), Padding = new Thickness(18, 10, 18, 10) }; WrapPanel actionFields = new WrapPanel { VerticalAlignment = VerticalAlignment.Center }; actionFields.Children.Add(FieldLabel("动作来源", 0)); actionFields.Children.Add(ReadOnlyField("产品DBC通信", 145)); actionFields.Children.Add(FieldLabel("目标设备/协议", 14)); actionFields.Children.Add(ReadOnlyField(messageName, 180)); actionFields.Children.Add(FieldLabel("功能", 14)); actionFields.Children.Add(ReadOnlyField(mode, 125)); actionFields.Children.Add(FieldLabel("动作名称", 14)); _stepName = new TextBox { Text = string.IsNullOrWhiteSpace(stepName) ? "新动作（未配置）" : stepName, Width = 270, Height = 34, Padding = new Thickness(9, 5, 9, 5), VerticalContentAlignment = VerticalAlignment.Center }; actionFields.Children.Add(_stepName); actionHeader.Child = actionFields; Grid.SetRow(actionHeader, 1); root.Children.Add(actionHeader);
            Grid body = new Grid { Margin = new Thickness(20, 14, 20, 12), Background = Brushes.White }; body.RowDefinitions.Add(new RowDefinition { Height = new GridLength(44) }); body.RowDefinitions.Add(new RowDefinition { Height = new GridLength(1, GridUnitType.Star) });
            DockPanel tools = new DockPanel { LastChildFill = false }; Grid searchHost = new Grid { Width = 340, Height = 34 }; _search = new TextBox { Height = 34, Padding = new Thickness(36, 6, 10, 6), Text = "搜索DBC信号", Foreground = Text(130, 142, 158), HorizontalAlignment = HorizontalAlignment.Stretch }; _search.GotKeyboardFocus += (s, e) => { if (_search.Text == "搜索DBC信号") { _search.Text = string.Empty; _search.Foreground = Text(37, 49, 67); } }; _search.LostKeyboardFocus += (s, e) => { if (string.IsNullOrWhiteSpace(_search.Text)) { _search.Text = "搜索DBC信号"; _search.Foreground = Text(130, 142, 158); } }; _search.TextChanged += (s, e) => _view.Refresh(); searchHost.Children.Add(_search); searchHost.Children.Add(new TextBlock { Text = "\uE721", FontFamily = new FontFamily("Segoe MDL2 Assets"), FontSize = 14, Foreground = Text(104, 117, 136), VerticalAlignment = VerticalAlignment.Center, HorizontalAlignment = HorizontalAlignment.Left, Margin = new Thickness(12, 0, 0, 0), IsHitTestVisible = false }); tools.Children.Add(searchHost); StackPanel filters = new StackPanel { Orientation = Orientation.Horizontal, Margin = new Thickness(10, 0, 0, 0) }; _allFilter = FilterButton("全部"); _selectedFilter = FilterButton("已选"); filters.Children.Add(_allFilter); filters.Children.Add(_selectedFilter); _allFilter.IsChecked = true; tools.Children.Add(filters); body.Children.Add(tools);
            _grid = new DataGrid { AutoGenerateColumns = false, CanUserAddRows = false, CanUserDeleteRows = false, RowHeight = 40, ColumnHeaderHeight = 38, GridLinesVisibility = DataGridGridLinesVisibility.Horizontal, BorderBrush = BorderColor(), BorderThickness = new Thickness(1), SelectionMode = DataGridSelectionMode.Extended, SelectionUnit = DataGridSelectionUnit.FullRow, HorizontalScrollBarVisibility = ScrollBarVisibility.Auto, VerticalScrollBarVisibility = ScrollBarVisibility.Auto, RowStyle = TableRowStyle(), Background = Brushes.White };
            Style headerStyle = new Style(typeof(DataGridColumnHeader)); headerStyle.Setters.Add(new Setter(Control.HorizontalContentAlignmentProperty, HorizontalAlignment.Center)); headerStyle.Setters.Add(new Setter(Control.VerticalContentAlignmentProperty, VerticalAlignment.Center)); headerStyle.Setters.Add(new Setter(Control.FontWeightProperty, FontWeights.SemiBold)); _grid.ColumnHeaderStyle = headerStyle; Style cellStyle = new Style(typeof(DataGridCell)); cellStyle.Setters.Add(new Setter(Control.VerticalContentAlignmentProperty, VerticalAlignment.Center)); _grid.CellStyle = cellStyle;
            Style centerCheck = BlueCheckStyle(); centerCheck.Setters.Add(new Setter(FrameworkElement.HorizontalAlignmentProperty, HorizontalAlignment.Center)); centerCheck.Setters.Add(new Setter(FrameworkElement.VerticalAlignmentProperty, VerticalAlignment.Center)); Style centerText = TextStyle(TextAlignment.Center, new Thickness(6, 0, 6, 0)); Style leftText = TextStyle(TextAlignment.Left, new Thickness(12, 0, 8, 0)); Style editorText = new Style(typeof(TextBox)); editorText.Setters.Add(new Setter(Control.HorizontalContentAlignmentProperty, HorizontalAlignment.Center)); editorText.Setters.Add(new Setter(Control.VerticalContentAlignmentProperty, VerticalAlignment.Center)); editorText.Setters.Add(new Setter(Control.PaddingProperty, new Thickness(6, 0, 6, 0)));
            _grid.Columns.Add(DataGridCheckHelpers.BoundCheckColumn(_readMode ? "读取" : "使用", "Use", 72, centerCheck)); _grid.Columns.Add(new DataGridTextColumn { Header = "信号", Binding = new Binding("Name"), Width = 300, IsReadOnly = true, ElementStyle = leftText }); _grid.Columns.Add(new DataGridTextColumn { Header = _readMode ? "当前值" : "实际值（可编辑）", Binding = new Binding("ValueText") { Mode = BindingMode.TwoWay, UpdateSourceTrigger = UpdateSourceTrigger.PropertyChanged }, Width = 150, IsReadOnly = _readMode, ElementStyle = centerText, EditingElementStyle = editorText }); _grid.Columns.Add(new DataGridTextColumn { Header = "单位", Binding = new Binding("Unit"), Width = 90, IsReadOnly = true, ElementStyle = centerText }); _grid.Columns.Add(new DataGridTextColumn { Header = "原始范围", Binding = new Binding("RawRange"), Width = 165, IsReadOnly = true, ElementStyle = centerText }); _grid.Columns.Add(new DataGridTextColumn { Header = "枚举说明", Binding = new Binding("EnumText"), Width = new DataGridLength(1, DataGridLengthUnitType.Star), IsReadOnly = true, ElementStyle = leftText }); _view = new ListCollectionView(_rows); _view.Filter = FilterRow; _grid.ItemsSource = _view; Grid.SetRow(_grid, 1); body.Children.Add(_grid); Grid.SetRow(body, 1); root.Children.Add(body);
            DockPanel footerPanel = new DockPanel { Background = Brushes.White }; _footer = new TextBlock { Foreground = Text(66, 79, 97), VerticalAlignment = VerticalAlignment.Center, Margin = new Thickness(22, 0, 0, 0) }; footerPanel.Children.Add(_footer); StackPanel buttons = new StackPanel { Orientation = Orientation.Horizontal, Margin = new Thickness(0, 14, 18, 14) }; DockPanel.SetDock(buttons, Dock.Right); Button cancel = SecondaryButton("取消"); cancel.Click += (s, e) => DialogResult = false; Button apply = PrimaryButton("应用配置"); apply.Click += Apply; buttons.Children.Add(cancel); if (_run != null) { Button runButton = SecondaryButton("立即运行"); runButton.Foreground = new SolidColorBrush(Color.FromRgb(24, 112, 224)); runButton.Click += Run_Click; buttons.Children.Add(runButton); } buttons.Children.Add(apply); footerPanel.Children.Insert(0, buttons); Grid.SetRow(footerPanel, 2); root.Children.Add(footerPanel); shell.Child = root; Content = shell;
            _useHeader = new CheckBox { Content = _readMode ? "读取" : "使用", IsThreeState = true, HorizontalAlignment = HorizontalAlignment.Center, VerticalAlignment = VerticalAlignment.Center, Cursor = Cursors.Hand }; _useHeader.Click += (s, e) => { if (_useHeader.IsChecked == true) SetAll(true); else if (_useHeader.IsChecked == false) SetAll(false); }; _grid.Columns[0].Header = _useHeader; Grid.SetRow(body, 2); Grid.SetRow(footerPanel, 3); foreach (DbcSignalEditRow row in _rows) row.PropertyChanged += RowChanged; RefreshFooter();
        }

        private static TextBlock FieldLabel(string text, double left) { return new TextBlock { Text = text, VerticalAlignment = VerticalAlignment.Center, Margin = new Thickness(left, 0, 8, 0) }; }
        private static TextBox ReadOnlyField(string text, double width) { return new TextBox { Text = text ?? string.Empty, Width = width, Height = 34, IsReadOnly = true, Padding = new Thickness(9, 5, 9, 5), VerticalContentAlignment = VerticalAlignment.Center, Background = new SolidColorBrush(Color.FromRgb(242, 245, 249)), BorderBrush = BorderColor() }; }
        private ToggleButton FilterButton(string text) { ToggleButton button = new ToggleButton { Content = text, MinWidth = 94, Height = 34, Style = SegmentStyle(), Margin = new Thickness(0), Cursor = Cursors.Hand }; button.Click += (s, e) => { _filter = text; if (_allFilter != null) _allFilter.IsChecked = ReferenceEquals(button, _allFilter); if (_selectedFilter != null) _selectedFilter.IsChecked = ReferenceEquals(button, _selectedFilter); _view.Refresh(); }; return button; }
        private bool FilterRow(object value) { DbcSignalEditRow row = value as DbcSignalEditRow; if (row == null) return false; string search = _search.Text == "搜索DBC信号" ? string.Empty : (_search.Text ?? string.Empty).Trim(); return (search.Length == 0 || (row.Name + " " + row.Unit + " " + row.RawRange + " " + row.EnumText).IndexOf(search, StringComparison.OrdinalIgnoreCase) >= 0) && (_filter == "全部" || row.Use); }
        private void RowChanged(object sender, PropertyChangedEventArgs e) { DbcSignalEditRow row = sender as DbcSignalEditRow; if (_readMode && !_guard && e.PropertyName == "Use" && row != null && row.Use) { _guard = true; foreach (DbcSignalEditRow other in _rows.Where(value => value != row && value.Use)) other.Use = false; _guard = false; } RefreshFooter(); if (_filter == "已选") _view.Refresh(); }
        private void SetAll(bool selected) { if (_readMode && selected) { DbcSignalEditRow first = _rows.FirstOrDefault(); if (first != null) first.Use = true; return; } foreach (DbcSignalEditRow row in _rows) row.Use = selected; }
        private void RefreshFooter() { int selected = _rows.Count(value => value.Use); if (_useHeader != null) _useHeader.IsChecked = selected == 0 ? false : selected == _rows.Count ? true : (bool?)null; _footer.Text = "已选 " + selected + " / " + _rows.Count + (_readMode ? "  ·  读取模式仅允许选择一个信号" : ""); }
        private bool CommitConfiguration() { _grid.CommitEdit(DataGridEditingUnit.Cell, true); _grid.CommitEdit(DataGridEditingUnit.Row, true); List<DbcSignalEditRow> selected = _rows.Where(value => value.Use).ToList(); if (selected.Count == 0) { MessageBox.Show(this, "请至少选择一个DBC信号。", "DBC信号配置", MessageBoxButton.OK, MessageBoxImage.Information); return false; } if (_readMode && selected.Count != 1) { MessageBox.Show(this, "读取DBC信号时只能选择一个信号。", "DBC信号配置", MessageBoxButton.OK, MessageBoxImage.Information); return false; } foreach (DbcSignalEditRow edit in _rows) { DbcSignalEditRow original = _sourceRows.FirstOrDefault(value => ReferenceEquals(value.Signal, edit.Signal) || value.Name == edit.Name); if (original != null) original.CopyConfigurationFrom(edit); } return true; }
        private void Apply(object sender, RoutedEventArgs e) { if (CommitConfiguration()) DialogResult = true; }
        private async void Run_Click(object sender, RoutedEventArgs e) { if (_run == null || !CommitConfiguration()) return; try { _footer.Text = "正在运行：" + StepName; string result = await _run(StepName); _footer.Text = "运行结果：" + result; } catch (Exception ex) { _footer.Text = "运行失败：" + ex.Message; MessageBox.Show(this, ex.Message, "立即运行", MessageBoxButton.OK, MessageBoxImage.Error); } }
        private static Button PrimaryButton(string text) { return new Button { Content = text, MinWidth = 116, Height = 34, Padding = new Thickness(16, 5, 16, 5), Margin = new Thickness(8, 0, 0, 0), Background = new SolidColorBrush(Color.FromRgb(24, 112, 224)), Foreground = Brushes.White, BorderBrush = new SolidColorBrush(Color.FromRgb(24, 112, 224)), BorderThickness = new Thickness(1) }; }
        private static Button SecondaryButton(string text) { return new Button { Content = text, MinWidth = 94, Height = 34, Padding = new Thickness(14, 5, 14, 5), Margin = new Thickness(8, 0, 0, 0), Background = Brushes.White, Foreground = Text(52, 67, 88), BorderBrush = BorderColor(), BorderThickness = new Thickness(1) }; }
        private static Style TableRowStyle() { Style style = new Style(typeof(DataGridRow)); style.Setters.Add(new Setter(Control.BackgroundProperty, Brushes.White)); style.Setters.Add(new Setter(Control.BorderBrushProperty, Brushes.Transparent)); style.Setters.Add(new Setter(Control.BorderThicknessProperty, new Thickness(3, 0, 0, 0))); Trigger selected = new Trigger { Property = DataGridRow.IsSelectedProperty, Value = true }; selected.Setters.Add(new Setter(Control.BackgroundProperty, new SolidColorBrush(Color.FromRgb(235, 244, 255)))); selected.Setters.Add(new Setter(Control.BorderBrushProperty, new SolidColorBrush(Color.FromRgb(24, 112, 224)))); style.Triggers.Add(selected); return style; }
        private static Style SegmentStyle() { Style style = new Style(typeof(ToggleButton)); style.Setters.Add(new Setter(Control.BackgroundProperty, Brushes.White)); style.Setters.Add(new Setter(Control.ForegroundProperty, Text(52, 67, 88))); style.Setters.Add(new Setter(Control.BorderBrushProperty, BorderColor())); style.Setters.Add(new Setter(Control.BorderThicknessProperty, new Thickness(1))); FrameworkElementFactory border = new FrameworkElementFactory(typeof(System.Windows.Controls.Border)); border.SetBinding(System.Windows.Controls.Border.BackgroundProperty, new Binding("Background") { RelativeSource = new RelativeSource(RelativeSourceMode.TemplatedParent) }); border.SetBinding(System.Windows.Controls.Border.BorderBrushProperty, new Binding("BorderBrush") { RelativeSource = new RelativeSource(RelativeSourceMode.TemplatedParent) }); border.SetBinding(System.Windows.Controls.Border.BorderThicknessProperty, new Binding("BorderThickness") { RelativeSource = new RelativeSource(RelativeSourceMode.TemplatedParent) }); FrameworkElementFactory content = new FrameworkElementFactory(typeof(ContentPresenter)); content.SetValue(FrameworkElement.HorizontalAlignmentProperty, HorizontalAlignment.Center); content.SetValue(FrameworkElement.VerticalAlignmentProperty, VerticalAlignment.Center); content.SetBinding(ContentPresenter.ContentProperty, new Binding("Content") { RelativeSource = new RelativeSource(RelativeSourceMode.TemplatedParent) }); border.AppendChild(content); style.Setters.Add(new Setter(Control.TemplateProperty, new ControlTemplate(typeof(ToggleButton)) { VisualTree = border })); Trigger selected = new Trigger { Property = ToggleButton.IsCheckedProperty, Value = true }; selected.Setters.Add(new Setter(Control.BackgroundProperty, new SolidColorBrush(Color.FromRgb(24, 112, 224)))); selected.Setters.Add(new Setter(Control.ForegroundProperty, Brushes.White)); selected.Setters.Add(new Setter(Control.BorderBrushProperty, new SolidColorBrush(Color.FromRgb(24, 112, 224)))); style.Triggers.Add(selected); return style; }
        private static Style BlueCheckStyle() { Style style = new Style(typeof(CheckBox)); FrameworkElementFactory root = new FrameworkElementFactory(typeof(System.Windows.Controls.Border)); root.Name = "CheckBoxSquare"; root.SetValue(FrameworkElement.WidthProperty, 16d); root.SetValue(FrameworkElement.HeightProperty, 16d); root.SetValue(System.Windows.Controls.Border.BorderBrushProperty, new SolidColorBrush(Color.FromRgb(139, 151, 168))); root.SetValue(System.Windows.Controls.Border.BorderThicknessProperty, new Thickness(1)); FrameworkElementFactory mark = new FrameworkElementFactory(typeof(TextBlock)); mark.Name = "CheckMark"; mark.SetValue(TextBlock.TextProperty, "✓"); mark.SetValue(TextBlock.ForegroundProperty, Brushes.White); mark.SetValue(TextBlock.FontSizeProperty, 12d); mark.SetValue(TextBlock.FontWeightProperty, FontWeights.Bold); mark.SetValue(FrameworkElement.HorizontalAlignmentProperty, HorizontalAlignment.Center); mark.SetValue(FrameworkElement.VerticalAlignmentProperty, VerticalAlignment.Center); mark.SetValue(UIElement.VisibilityProperty, Visibility.Collapsed); root.AppendChild(mark); ControlTemplate template = new ControlTemplate(typeof(CheckBox)) { VisualTree = root }; Trigger on = new Trigger { Property = ToggleButton.IsCheckedProperty, Value = true }; on.Setters.Add(new Setter(System.Windows.Controls.Border.BackgroundProperty, new SolidColorBrush(Color.FromRgb(24, 112, 224)), "CheckBoxSquare")); on.Setters.Add(new Setter(System.Windows.Controls.Border.BorderBrushProperty, new SolidColorBrush(Color.FromRgb(24, 112, 224)), "CheckBoxSquare")); on.Setters.Add(new Setter(UIElement.VisibilityProperty, Visibility.Visible, "CheckMark")); template.Triggers.Add(on); style.Setters.Add(new Setter(Control.TemplateProperty, template)); return style; }
        private static Style TextStyle(TextAlignment alignment, Thickness margin) { Style style = new Style(typeof(TextBlock)); style.Setters.Add(new Setter(TextBlock.TextAlignmentProperty, alignment)); style.Setters.Add(new Setter(FrameworkElement.HorizontalAlignmentProperty, HorizontalAlignment.Stretch)); style.Setters.Add(new Setter(FrameworkElement.VerticalAlignmentProperty, VerticalAlignment.Center)); style.Setters.Add(new Setter(FrameworkElement.MarginProperty, margin)); style.Setters.Add(new Setter(TextBlock.TextTrimmingProperty, TextTrimming.CharacterEllipsis)); return style; }
        private static SolidColorBrush Text(byte r, byte g, byte b) { return new SolidColorBrush(Color.FromRgb(r, g, b)); }
        private static SolidColorBrush BorderColor() { return new SolidColorBrush(Color.FromRgb(211, 221, 234)); }
    }
}
