using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Media;
using System.Windows.Media.Effects;

namespace ManualCanDebug
{
    internal sealed class DbcSignalConfigurationWindow : Window
    {
        private readonly IList<DbcSignalEditRow> _sourceRows;
        private readonly ObservableCollection<DbcSignalEditRow> _rows;
        private readonly bool _readMode;
        private readonly ListCollectionView _view;
        private readonly ListBox _list;
        private readonly TextBox _search;
        private readonly Grid _details;
        private readonly Grid _valueRow;
        private readonly TextBlock _footer;
        private string _filter = "全部";
        private bool _guard;
        private ToggleButton _allFilter;
        private ToggleButton _selectedFilter;

        public DbcSignalConfigurationWindow(IEnumerable<DbcSignalEditRow> rows, string mode, string messageName)
        {
            _sourceRows = (rows ?? Enumerable.Empty<DbcSignalEditRow>()).ToList(); _rows = new ObservableCollection<DbcSignalEditRow>(_sourceRows.Select(value => value.CloneForEditing())); _readMode = string.Equals(mode, "读取DBC信号", StringComparison.Ordinal);
            Title = "DBC信号配置"; Width = 1100; Height = 680; MinWidth = 1100; MinHeight = 680; WindowStartupLocation = WindowStartupLocation.CenterOwner; WindowStyle = WindowStyle.None; AllowsTransparency = true; ResizeMode = ResizeMode.NoResize; Background = Brushes.Transparent; FontFamily = new FontFamily("Microsoft YaHei UI"); FontSize = 13; StudioControlTheme.Apply(Resources); Border shell = new Border { Background = Brushes.White, BorderBrush = Border(), BorderThickness = new Thickness(1), CornerRadius = new CornerRadius(8), Effect = new DropShadowEffect { BlurRadius = 18, ShadowDepth = 2, Opacity = 0.2, Color = Colors.SlateGray } };
            Grid root = new Grid(); root.RowDefinitions.Add(new RowDefinition { Height = new GridLength(58) }); root.RowDefinitions.Add(new RowDefinition { Height = new GridLength(1, GridUnitType.Star) }); root.RowDefinitions.Add(new RowDefinition { Height = new GridLength(64) });
            DockPanel header = new DockPanel { Background = Brushes.White }; header.MouseLeftButtonDown += (s, e) => { if (e.ButtonState == System.Windows.Input.MouseButtonState.Pressed) DragMove(); }; Button close = new Button { Content = "×", Width = 48, Height = 40, Margin = new Thickness(0, 7, 7, 7), FontSize = 22, Foreground = Text(92, 105, 123), Background = Brushes.Transparent, BorderThickness = new Thickness(0) }; close.Click += (s, e) => DialogResult = false; DockPanel.SetDock(close, Dock.Right); header.Children.Add(close); TextBlock meta = new TextBlock { Text = (messageName ?? string.Empty) + "  ·  " + mode, Foreground = Text(105, 118, 137), VerticalAlignment = VerticalAlignment.Center, Margin = new Thickness(10, 0, 16, 0) }; DockPanel.SetDock(meta, Dock.Right); header.Children.Add(meta); header.Children.Add(new TextBlock { Text = "DBC信号配置", FontSize = 18, FontWeight = FontWeights.SemiBold, Foreground = Text(32, 43, 59), VerticalAlignment = VerticalAlignment.Center, Margin = new Thickness(22, 0, 12, 0) }); root.Children.Add(header);
            Grid body = new Grid { Margin = new Thickness(18, 14, 18, 14), Background = Brushes.White }; body.ColumnDefinitions.Add(new ColumnDefinition { Width = new GridLength(390) }); body.ColumnDefinitions.Add(new ColumnDefinition { Width = new GridLength(1) }); body.ColumnDefinitions.Add(new ColumnDefinition { Width = new GridLength(1, GridUnitType.Star) });
            Grid left = new Grid { Margin = new Thickness(16) }; left.RowDefinitions.Add(new RowDefinition { Height = new GridLength(38) }); left.RowDefinitions.Add(new RowDefinition { Height = new GridLength(42) }); left.RowDefinitions.Add(new RowDefinition { Height = new GridLength(1, GridUnitType.Star) }); _search = new TextBox { Height = 32, Padding = new Thickness(10, 5, 10, 5), Text = "搜索DBC信号", Foreground = Text(130, 142, 158), ToolTip = "搜索DBC信号" }; _search.GotKeyboardFocus += (s, e) => { if (_search.Text == "搜索DBC信号") { _search.Text = string.Empty; _search.Foreground = Text(37, 49, 67); } }; _search.LostKeyboardFocus += (s, e) => { if (string.IsNullOrWhiteSpace(_search.Text)) { _search.Text = "搜索DBC信号"; _search.Foreground = Text(130, 142, 158); } }; _search.TextChanged += (s, e) => _view.Refresh(); left.Children.Add(_search); UniformGrid filters = new UniformGrid { Columns = 2, Margin = new Thickness(0, 7, 0, 5) }; _allFilter = FilterButton("全部"); _selectedFilter = FilterButton("已选"); filters.Children.Add(_allFilter); filters.Children.Add(_selectedFilter); _allFilter.IsChecked = true; _allFilter.Background = new SolidColorBrush(Color.FromRgb(24, 112, 224)); _allFilter.Foreground = Brushes.White; Grid.SetRow(filters, 1); left.Children.Add(filters); _list = new ListBox { BorderBrush = Border(), BorderThickness = new Thickness(1), HorizontalContentAlignment = HorizontalAlignment.Stretch }; _list.Resources[SystemColors.HighlightBrushKey] = new SolidColorBrush(Color.FromRgb(235, 244, 255)); _view = new ListCollectionView(_rows); _view.Filter = FilterRow; _list.ItemsSource = _view; _list.ItemTemplate = ItemTemplate(); _list.SelectionChanged += (s, e) => { if (_details != null) _details.DataContext = Current; }; Grid.SetRow(_list, 2); left.Children.Add(_list); body.Children.Add(left); Border divider = new Border { Background = Border() }; Grid.SetColumn(divider, 1); body.Children.Add(divider);
            _details = new Grid { Margin = new Thickness(28, 18, 28, 18) }; _details.RowDefinitions.Add(new RowDefinition { Height = new GridLength(50) }); _details.RowDefinitions.Add(new RowDefinition { Height = new GridLength(46) }); _details.RowDefinitions.Add(new RowDefinition { Height = new GridLength(50) }); _details.RowDefinitions.Add(new RowDefinition { Height = new GridLength(58) }); _details.RowDefinitions.Add(new RowDefinition { Height = new GridLength(1, GridUnitType.Star) }); _details.Children.Add(new TextBlock { Text = "当前信号配置", FontSize = 16, FontWeight = FontWeights.SemiBold, Foreground = Text(37, 49, 67), VerticalAlignment = VerticalAlignment.Center }); Border selectedHeader = new Border { Background = new SolidColorBrush(Color.FromRgb(240, 246, 254)), BorderBrush = new SolidColorBrush(Color.FromRgb(199, 218, 242)), BorderThickness = new Thickness(1), CornerRadius = new CornerRadius(4), Padding = new Thickness(12, 7, 12, 7) }; TextBlock selectedName = new TextBlock { FontWeight = FontWeights.SemiBold, FontSize = 14 }; selectedName.SetBinding(TextBlock.TextProperty, new Binding("Name")); selectedHeader.Child = selectedName; Grid.SetRow(selectedHeader, 1); _details.Children.Add(selectedHeader); CheckBox use = new CheckBox { Content = _readMode ? "读取该信号" : "发送该信号", VerticalAlignment = VerticalAlignment.Center }; use.SetBinding(ToggleButton.IsCheckedProperty, new Binding("Use") { Mode = BindingMode.TwoWay, UpdateSourceTrigger = UpdateSourceTrigger.PropertyChanged }); Grid.SetRow(use, 2); _details.Children.Add(use); _valueRow = new Grid(); _valueRow.ColumnDefinitions.Add(new ColumnDefinition { Width = new GridLength(120) }); _valueRow.ColumnDefinitions.Add(new ColumnDefinition { Width = new GridLength(260) }); _valueRow.Children.Add(new TextBlock { Text = "信号值", VerticalAlignment = VerticalAlignment.Center, Foreground = Text(37, 49, 67) }); TextBox value = new TextBox { Height = 32, Padding = new Thickness(8, 5, 8, 5) }; value.SetBinding(TextBox.TextProperty, new Binding("ValueText") { Mode = BindingMode.TwoWay, UpdateSourceTrigger = UpdateSourceTrigger.PropertyChanged }); Grid.SetColumn(value, 1); _valueRow.Children.Add(value); Grid.SetRow(_valueRow, 3); _details.Children.Add(_valueRow); TextBlock help = new TextBlock { Text = _readMode ? "读取操作只能选择一个DBC信号；LIMIT继续在结果与判断区域配置。" : "选择要发送的信号并填写实际值，应用后自动更新SignalsJson和原始DATA。", Foreground = Text(104, 117, 136), TextWrapping = TextWrapping.Wrap, Margin = new Thickness(0, 12, 0, 0) }; Grid.SetRow(help, 4); _details.Children.Add(help); _valueRow.Visibility = _readMode ? Visibility.Collapsed : Visibility.Visible; Grid.SetColumn(_details, 2); body.Children.Add(_details); Grid.SetRow(body, 1); root.Children.Add(body);
            DockPanel footerPanel = new DockPanel { Background = Brushes.White }; _footer = new TextBlock { Foreground = Text(66, 79, 97), VerticalAlignment = VerticalAlignment.Center, Margin = new Thickness(22, 0, 0, 0) }; footerPanel.Children.Add(_footer); StackPanel buttons = new StackPanel { Orientation = Orientation.Horizontal, Margin = new Thickness(0, 14, 18, 14) }; DockPanel.SetDock(buttons, Dock.Right); Button cancel = SecondaryButton("取消"); cancel.Click += (s, e) => DialogResult = false; Button apply = PrimaryButton("应用配置"); apply.Click += Apply; buttons.Children.Add(cancel); buttons.Children.Add(apply); footerPanel.Children.Insert(0, buttons); Grid.SetRow(footerPanel, 2); root.Children.Add(footerPanel); shell.Child = root; Content = shell;
            foreach (DbcSignalEditRow row in _rows) row.PropertyChanged += RowChanged; _list.SelectedItem = _rows.FirstOrDefault(valueRow => valueRow.Use) ?? _rows.FirstOrDefault(); _details.DataContext = Current; RefreshFooter();
        }

        private DbcSignalEditRow Current { get { return _list.SelectedItem as DbcSignalEditRow; } }
        private ToggleButton FilterButton(string text) { ToggleButton button = new ToggleButton { Content = text, Height = 34, Margin = new Thickness(0), Background = Brushes.White, BorderBrush = Border(), BorderThickness = new Thickness(1) }; button.Click += (s, e) => { _filter = text; _allFilter.IsChecked = ReferenceEquals(button, _allFilter); _selectedFilter.IsChecked = ReferenceEquals(button, _selectedFilter); button.Background = new SolidColorBrush(Color.FromRgb(24, 112, 224)); button.Foreground = Brushes.White; ToggleButton other = ReferenceEquals(button, _allFilter) ? _selectedFilter : _allFilter; if (other != null) { other.Background = Brushes.White; other.Foreground = Text(52, 67, 88); } _view.Refresh(); }; return button; }
        private bool FilterRow(object value) { DbcSignalEditRow row = value as DbcSignalEditRow; if (row == null) return false; string search = _search.Text == "搜索DBC信号" ? string.Empty : (_search.Text ?? string.Empty).Trim(); return (search.Length == 0 || (row.Name + " " + row.Unit + " " + row.RawRange).IndexOf(search, StringComparison.OrdinalIgnoreCase) >= 0) && (_filter == "全部" || row.Use); }
        private void RowChanged(object sender, PropertyChangedEventArgs e) { DbcSignalEditRow row = sender as DbcSignalEditRow; if (_readMode && !_guard && e.PropertyName == "Use" && row != null && row.Use) { _guard = true; foreach (DbcSignalEditRow other in _rows.Where(value => value != row && value.Use)) other.Use = false; _guard = false; } RefreshFooter(); if (_filter == "已选") _view.Refresh(); }
        private void RefreshFooter() { _footer.Text = "已选 " + _rows.Count(value => value.Use) + " / " + _rows.Count; }
        private void Apply(object sender, RoutedEventArgs e) { List<DbcSignalEditRow> selected = _rows.Where(value => value.Use).ToList(); if (selected.Count == 0) { MessageBox.Show(this, "请至少选择一个DBC信号。", "DBC信号配置", MessageBoxButton.OK, MessageBoxImage.Information); return; } if (_readMode && selected.Count != 1) { MessageBox.Show(this, "读取DBC信号时只能选择一个信号。", "DBC信号配置", MessageBoxButton.OK, MessageBoxImage.Information); return; } foreach (DbcSignalEditRow edit in _rows) { DbcSignalEditRow original = _sourceRows.FirstOrDefault(value => ReferenceEquals(value.Signal, edit.Signal) || value.Name == edit.Name); if (original != null) original.CopyConfigurationFrom(edit); } DialogResult = true; }
        private static DataTemplate ItemTemplate() { FrameworkElementFactory row = new FrameworkElementFactory(typeof(DockPanel)); row.SetValue(DockPanel.LastChildFillProperty, true); FrameworkElementFactory check = new FrameworkElementFactory(typeof(CheckBox)); check.SetBinding(ToggleButton.IsCheckedProperty, new Binding("Use") { Mode = BindingMode.TwoWay, UpdateSourceTrigger = UpdateSourceTrigger.PropertyChanged }); check.SetValue(DockPanel.DockProperty, Dock.Left); check.SetValue(FrameworkElement.MarginProperty, new Thickness(10, 8, 10, 8)); row.AppendChild(check); FrameworkElementFactory stack = new FrameworkElementFactory(typeof(StackPanel)); stack.SetValue(FrameworkElement.MarginProperty, new Thickness(0, 6, 8, 6)); FrameworkElementFactory name = new FrameworkElementFactory(typeof(TextBlock)); name.SetBinding(TextBlock.TextProperty, new Binding("Name")); name.SetValue(TextBlock.FontWeightProperty, FontWeights.SemiBold); stack.AppendChild(name); FrameworkElementFactory meta = new FrameworkElementFactory(typeof(TextBlock)); MultiBinding binding = new MultiBinding { StringFormat = "{0}  ·  {1}" }; binding.Bindings.Add(new Binding("Unit")); binding.Bindings.Add(new Binding("RawRange")); meta.SetBinding(TextBlock.TextProperty, binding); meta.SetValue(TextBlock.FontSizeProperty, 11d); meta.SetValue(TextBlock.ForegroundProperty, Text(110, 123, 142)); stack.AppendChild(meta); row.AppendChild(stack); return new DataTemplate { VisualTree = row }; }
        private static Button PrimaryButton(string text) { return new Button { Content = text, MinWidth = 116, Height = 34, Padding = new Thickness(16, 5, 16, 5), Margin = new Thickness(8, 0, 0, 0), Background = new SolidColorBrush(Color.FromRgb(24, 112, 224)), Foreground = Brushes.White, BorderBrush = new SolidColorBrush(Color.FromRgb(24, 112, 224)), BorderThickness = new Thickness(1) }; }
        private static Button SecondaryButton(string text) { return new Button { Content = text, MinWidth = 94, Height = 34, Padding = new Thickness(14, 5, 14, 5), Margin = new Thickness(8, 0, 0, 0), Background = Brushes.White, Foreground = Text(52, 67, 88), BorderBrush = Border(), BorderThickness = new Thickness(1) }; }
        private static SolidColorBrush Text(byte r, byte g, byte b) { return new SolidColorBrush(Color.FromRgb(r, g, b)); }
        private static SolidColorBrush Border() { return new SolidColorBrush(Color.FromRgb(211, 221, 234)); }
    }
}
