using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Media;

namespace ManualCanDebug
{
    internal sealed class InstrumentActionManagerWindow : Window
    {
        private readonly List<InstrumentActionDefinition> _other;
        private readonly ObservableCollection<InstrumentActionDefinition> _actions;
        private readonly ObservableCollection<InstrumentActionFieldDefinition> _fields = new ObservableCollection<InstrumentActionFieldDefinition>();
        private readonly DataGrid _actionGrid, _fieldGrid;
        private InstrumentActionDefinition _previousAction;

        public InstrumentActionManagerWindow()
        {
            Title = "仪器与动作管理"; Width = 1380; Height = 760; MinWidth = 1100; MinHeight = 620; WindowStartupLocation = WindowStartupLocation.CenterOwner; FontFamily = new FontFamily("Segoe UI"); FontSize = 12;
            List<InstrumentActionDefinition> all = ActionCatalog.LoadDefinitions().ToList(); _other = all.Where(value => !string.Equals(value.Source, "仪器", StringComparison.OrdinalIgnoreCase)).ToList(); _actions = new ObservableCollection<InstrumentActionDefinition>(all.Where(value => string.Equals(value.Source, "仪器", StringComparison.OrdinalIgnoreCase)));
            Grid root = new Grid { Margin = new Thickness(16) }; root.RowDefinitions.Add(new RowDefinition { Height = GridLength.Auto }); root.RowDefinitions.Add(new RowDefinition { Height = new GridLength(3, GridUnitType.Star) }); root.RowDefinitions.Add(new RowDefinition { Height = new GridLength(8) }); root.RowDefinitions.Add(new RowDefinition { Height = new GridLength(2, GridUnitType.Star) }); root.RowDefinitions.Add(new RowDefinition { Height = GridLength.Auto });
            DockPanel header = new DockPanel { Margin = new Thickness(0, 0, 0, 8) }; StackPanel actionButtons = new StackPanel { Orientation = Orientation.Horizontal }; DockPanel.SetDock(actionButtons, Dock.Right); actionButtons.Children.Add(Button("＋ 新增仪器/动作", AddAction)); actionButtons.Children.Add(Button("复制动作", CopyAction)); actionButtons.Children.Add(Button("删除动作", DeleteAction)); actionButtons.Children.Add(Button("删除整个仪器", DeleteInstrument)); header.Children.Add(actionButtons); header.Children.Add(new TextBlock { Text = "仪器动作目录", FontSize = 18, FontWeight = FontWeights.SemiBold, VerticalAlignment = VerticalAlignment.Center }); root.Children.Add(header);
            _actionGrid = new DataGrid { ItemsSource = _actions, AutoGenerateColumns = false, CanUserAddRows = false, SelectionUnit = DataGridSelectionUnit.FullRow, RowHeight = 34, ColumnHeaderHeight = 34, HorizontalScrollBarVisibility = ScrollBarVisibility.Auto }; AddText(_actionGrid, "仪器名称", "Target", 150); AddText(_actionGrid, "动作名称", "DisplayName", 150); AddText(_actionGrid, "Device", "Device", 90); AddText(_actionGrid, "Operation", "Operation", 120); _actionGrid.Columns.Add(new DataGridComboBoxColumn { Header = "绑定方式", SelectedItemBinding = new Binding("BindingMode") { UpdateSourceTrigger = UpdateSourceTrigger.PropertyChanged }, ItemsSource = new[] { "Generic", "MainTest", "Plugin" }, Width = 105 }); AddText(_actionGrid, "MAINTEST函数", "FunctionName", 170); AddText(_actionGrid, "插件DLL", "PluginAssembly", 210); AddText(_actionGrid, "插件类型", "PluginType", 230); _actionGrid.Columns.Add(new DataGridCheckBoxColumn { Header = "返回值", Binding = new Binding("ReturnsValue"), Width = 70 }); _actionGrid.SelectionChanged += ActionSelectionChanged; Grid.SetRow(_actionGrid, 1); root.Children.Add(_actionGrid);
            GridSplitter splitter = new GridSplitter { HorizontalAlignment = HorizontalAlignment.Stretch, VerticalAlignment = VerticalAlignment.Stretch, Background = new SolidColorBrush(Color.FromRgb(215, 224, 236)), ResizeDirection = GridResizeDirection.Rows, ResizeBehavior = GridResizeBehavior.PreviousAndNext }; Grid.SetRow(splitter, 2); root.Children.Add(splitter);
            Grid parameter = new Grid(); parameter.RowDefinitions.Add(new RowDefinition { Height = GridLength.Auto }); parameter.RowDefinitions.Add(new RowDefinition { Height = new GridLength(1, GridUnitType.Star) }); DockPanel parameterHeader = new DockPanel { Margin = new Thickness(0, 8, 0, 6) }; StackPanel fieldButtons = new StackPanel { Orientation = Orientation.Horizontal }; DockPanel.SetDock(fieldButtons, Dock.Right); fieldButtons.Children.Add(Button("＋ 新增参数", AddField)); fieldButtons.Children.Add(Button("删除参数", DeleteField)); parameterHeader.Children.Add(fieldButtons); parameterHeader.Children.Add(new TextBlock { Text = "选中动作的参数", FontSize = 15, FontWeight = FontWeights.SemiBold, VerticalAlignment = VerticalAlignment.Center }); parameter.Children.Add(parameterHeader); _fieldGrid = new DataGrid { ItemsSource = _fields, AutoGenerateColumns = false, CanUserAddRows = false, SelectionUnit = DataGridSelectionUnit.FullRow, RowHeight = 33, ColumnHeaderHeight = 33 }; AddText(_fieldGrid, "参数名", "Name", 150); AddText(_fieldGrid, "显示名称", "Label", 180); _fieldGrid.Columns.Add(new DataGridComboBoxColumn { Header = "类型", SelectedItemBinding = new Binding("Type") { UpdateSourceTrigger = UpdateSourceTrigger.PropertyChanged }, ItemsSource = new[] { "double", "int", "bool", "string" }, Width = 100 }); AddText(_fieldGrid, "默认值", "DefaultValue", 130); AddText(_fieldGrid, "单位", "Unit", 90); AddText(_fieldGrid, "选项（|分隔）", "Options", 350); Grid.SetRow(_fieldGrid, 1); parameter.Children.Add(_fieldGrid); Grid.SetRow(parameter, 3); root.Children.Add(parameter);
            DockPanel footer = new DockPanel { Margin = new Thickness(0, 12, 0, 0) }; TextBlock hint = new TextBlock { Text = "Generic用于内置通用Device；MainTest直接绑定TestDllMain函数；Plugin需要实现Execute(string operation, string parametersJson)。删除某仪器的全部动作即删除该仪器。", Foreground = Brushes.DimGray, TextWrapping = TextWrapping.Wrap, VerticalAlignment = VerticalAlignment.Center }; StackPanel saveButtons = new StackPanel { Orientation = Orientation.Horizontal }; DockPanel.SetDock(saveButtons, Dock.Right); saveButtons.Children.Add(Button("取消", (s, e) => DialogResult = false)); Button save = Button("保存配置", Save); save.Background = new SolidColorBrush(Color.FromRgb(24, 112, 224)); save.Foreground = Brushes.White; saveButtons.Children.Add(save); footer.Children.Add(saveButtons); footer.Children.Add(hint); Grid.SetRow(footer, 4); root.Children.Add(footer); Content = root; if (_actions.Count > 0) { _actionGrid.SelectedIndex = 0; if (_fields.Count == 0) foreach (InstrumentActionFieldDefinition field in _actions[0].Fields ?? new List<InstrumentActionFieldDefinition>()) _fields.Add(field); }
        }

        private void ActionSelectionChanged(object sender, SelectionChangedEventArgs e) { CommitFields(); _fields.Clear(); InstrumentActionDefinition selected = _actionGrid.SelectedItem as InstrumentActionDefinition; if (selected != null) foreach (InstrumentActionFieldDefinition field in selected.Fields ?? new List<InstrumentActionFieldDefinition>()) _fields.Add(field); _previousAction = selected; }
        private void CommitFields() { if (_previousAction != null) _previousAction.Fields = _fields.ToList(); }
        private void AddAction(object sender, RoutedEventArgs e) { CommitFields(); InstrumentActionDefinition action = new InstrumentActionDefinition(); _actions.Add(action); _actionGrid.SelectedItem = action; _actionGrid.ScrollIntoView(action); }
        private void CopyAction(object sender, RoutedEventArgs e) { CommitFields(); InstrumentActionDefinition value = _actionGrid.SelectedItem as InstrumentActionDefinition; if (value == null) return; InstrumentActionDefinition copy = new InstrumentActionDefinition { Source = "仪器", Target = value.Target, Device = value.Device, Operation = value.Operation, DisplayName = value.DisplayName + " - 副本", ReturnsValue = value.ReturnsValue, BindingMode = value.BindingMode, FunctionName = value.FunctionName, PluginAssembly = value.PluginAssembly, PluginType = value.PluginType, Fields = (value.Fields ?? new List<InstrumentActionFieldDefinition>()).Select(CloneField).ToList() }; _actions.Add(copy); _actionGrid.SelectedItem = copy; }
        private void DeleteAction(object sender, RoutedEventArgs e) { InstrumentActionDefinition value = _actionGrid.SelectedItem as InstrumentActionDefinition; if (value != null) _actions.Remove(value); }
        private void DeleteInstrument(object sender, RoutedEventArgs e) { InstrumentActionDefinition value = _actionGrid.SelectedItem as InstrumentActionDefinition; if (value == null) return; string target = value.Target; if (MessageBox.Show(this, "删除仪器“" + target + "”及其全部动作？", "删除仪器", MessageBoxButton.YesNo, MessageBoxImage.Warning) != MessageBoxResult.Yes) return; foreach (InstrumentActionDefinition action in _actions.Where(item => string.Equals(item.Target, target, StringComparison.OrdinalIgnoreCase)).ToList()) _actions.Remove(action); }
        private void AddField(object sender, RoutedEventArgs e) { InstrumentActionFieldDefinition field = new InstrumentActionFieldDefinition(); _fields.Add(field); _fieldGrid.SelectedItem = field; }
        private void DeleteField(object sender, RoutedEventArgs e) { InstrumentActionFieldDefinition field = _fieldGrid.SelectedItem as InstrumentActionFieldDefinition; if (field != null) _fields.Remove(field); }
        private void Save(object sender, RoutedEventArgs e) { _actionGrid.CommitEdit(DataGridEditingUnit.Cell, true); _actionGrid.CommitEdit(DataGridEditingUnit.Row, true); _fieldGrid.CommitEdit(DataGridEditingUnit.Cell, true); _fieldGrid.CommitEdit(DataGridEditingUnit.Row, true); CommitFields(); if (_actions.Any(value => string.IsNullOrWhiteSpace(value.Target) || string.IsNullOrWhiteSpace(value.DisplayName))) { MessageBox.Show(this, "仪器名称和动作名称不能为空。", "仪器动作", MessageBoxButton.OK, MessageBoxImage.Information); return; } ActionCatalog.SaveDefinitions(_other.Concat(_actions)); DialogResult = true; }
        private static InstrumentActionFieldDefinition CloneField(InstrumentActionFieldDefinition value) { return new InstrumentActionFieldDefinition { Name = value.Name, Label = value.Label, Type = value.Type, DefaultValue = value.DefaultValue, Unit = value.Unit, Options = value.Options }; }
        private static Button Button(string text, RoutedEventHandler handler) { Button value = new Button { Content = text, MinWidth = 86, Margin = new Thickness(4), Padding = new Thickness(10, 5, 10, 5) }; value.Click += handler; return value; }
        private static void AddText(DataGrid grid, string header, string path, double width) { grid.Columns.Add(new DataGridTextColumn { Header = header, Binding = new Binding(path) { UpdateSourceTrigger = UpdateSourceTrigger.PropertyChanged }, Width = width }); }
        private static void AddText(DataGrid grid, string header, string path, DataGridLength width) { grid.Columns.Add(new DataGridTextColumn { Header = header, Binding = new Binding(path) { UpdateSourceTrigger = UpdateSourceTrigger.PropertyChanged }, Width = width }); }
    }
}
