using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Globalization;
using System.Linq;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Input;
using System.Windows.Media;

namespace ManualCanDebug
{
    internal sealed class LocatorSignalConfigurationWindow : Window
    {
        private readonly IList<LocatorSignalRow> _sourceRows;
        private readonly ObservableCollection<LocatorSignalRow> _rows;
        private readonly bool _writeMode;
        private readonly bool _singleMode;
        private readonly ListCollectionView _view;
        private readonly ListBox _signalList;
        private readonly TextBox _search;
        private readonly TextBlock _footerSummary;
        private readonly Grid _details;
        private readonly CheckBox _use;
        private readonly CheckBox _needsJudgment;
        private readonly RadioButton _informationMode;
        private readonly RadioButton _numericMode;
        private readonly RadioButton _stringMode;
        private readonly Grid _numericFields;
        private readonly Grid _stringFields;
        private readonly Grid _writeFields;
        private string _filterMode = "全部";
        private bool _updating;

        public LocatorSignalConfigurationWindow(IEnumerable<LocatorSignalRow> rows, string operation, string tableName)
        {
            _sourceRows = (rows ?? Enumerable.Empty<LocatorSignalRow>()).ToList(); _rows = new ObservableCollection<LocatorSignalRow>(_sourceRows.Select(value => value.CloneForEditing())); _writeMode = (operation ?? string.Empty).Contains("写入"); _singleMode = (operation ?? string.Empty).Contains("单信号");
            Title = "信号与判定配置"; Width = 1180; Height = 720; MinWidth = 980; MinHeight = 620; WindowStartupLocation = WindowStartupLocation.CenterOwner; ResizeMode = ResizeMode.CanResize; Background = new SolidColorBrush(Color.FromRgb(245, 247, 250)); FontFamily = new FontFamily("Microsoft YaHei UI"); FontSize = 13;
            Grid root = new Grid(); root.RowDefinitions.Add(new RowDefinition { Height = new GridLength(58) }); root.RowDefinitions.Add(new RowDefinition { Height = new GridLength(1, GridUnitType.Star) }); root.RowDefinitions.Add(new RowDefinition { Height = new GridLength(64) });
            DockPanel header = new DockPanel { Background = Brushes.White, LastChildFill = true, Margin = new Thickness(0), }; header.Children.Add(new TextBlock { Text = "信号与判定配置", FontSize = 17, FontWeight = FontWeights.SemiBold, Foreground = Text(32, 43, 59), VerticalAlignment = VerticalAlignment.Center, Margin = new Thickness(22, 0, 12, 0) }); TextBlock table = new TextBlock { Text = (tableName ?? string.Empty) + "  ·  " + operation, Foreground = Text(105, 118, 137), VerticalAlignment = VerticalAlignment.Center, Margin = new Thickness(10, 0, 22, 0) }; DockPanel.SetDock(table, Dock.Right); header.Children.Insert(0, table); root.Children.Add(header);
            Grid body = new Grid { Margin = new Thickness(18, 14, 18, 14), Background = Brushes.White }; body.ColumnDefinitions.Add(new ColumnDefinition { Width = new GridLength(390) }); body.ColumnDefinitions.Add(new ColumnDefinition { Width = new GridLength(1) }); body.ColumnDefinitions.Add(new ColumnDefinition { Width = new GridLength(1, GridUnitType.Star) });
            Grid left = new Grid { Margin = new Thickness(16) }; left.RowDefinitions.Add(new RowDefinition { Height = new GridLength(38) }); left.RowDefinitions.Add(new RowDefinition { Height = new GridLength(42) }); left.RowDefinitions.Add(new RowDefinition { Height = new GridLength(1, GridUnitType.Star) });
            _search = new TextBox { Height = 32, Padding = new Thickness(10, 5, 10, 5), Text = "搜索信号名称", Foreground = Text(130, 142, 158), ToolTip = "搜索信号名称、Offset或类型" }; _search.GotKeyboardFocus += (s, e) => { if (_search.Text == "搜索信号名称") { _search.Text = string.Empty; _search.Foreground = Text(37, 49, 67); } }; _search.LostKeyboardFocus += (s, e) => { if (string.IsNullOrWhiteSpace(_search.Text)) { _search.Text = "搜索信号名称"; _search.Foreground = Text(130, 142, 158); } }; _search.TextChanged += (s, e) => _view.Refresh(); left.Children.Add(_search);
            UniformGrid filters = new UniformGrid { Columns = 3, Margin = new Thickness(0, 7, 0, 5) }; filters.Children.Add(FilterButton("全部")); filters.Children.Add(FilterButton("已选")); filters.Children.Add(FilterButton("有判断")); Grid.SetRow(filters, 1); left.Children.Add(filters);
            _signalList = new ListBox { BorderBrush = Border(), BorderThickness = new Thickness(1), HorizontalContentAlignment = HorizontalAlignment.Stretch, SelectionMode = SelectionMode.Single };
            _view = new ListCollectionView(_rows); _view.Filter = FilterSignal; _signalList.ItemsSource = _view; _signalList.ItemTemplate = SignalTemplate(); _signalList.SelectionChanged += SignalSelectionChanged; Grid.SetRow(_signalList, 2); left.Children.Add(_signalList); body.Children.Add(left);
            Border divider = new Border { Background = Border() }; Grid.SetColumn(divider, 1); body.Children.Add(divider);
            _details = new Grid { Margin = new Thickness(28, 18, 28, 18) }; _details.RowDefinitions.Add(new RowDefinition { Height = new GridLength(50) }); _details.RowDefinitions.Add(new RowDefinition { Height = new GridLength(42) }); _details.RowDefinitions.Add(new RowDefinition { Height = new GridLength(46) }); _details.RowDefinitions.Add(new RowDefinition { Height = new GridLength(48) }); _details.RowDefinitions.Add(new RowDefinition { Height = new GridLength(86) }); _details.RowDefinitions.Add(new RowDefinition { Height = new GridLength(56) }); _details.RowDefinitions.Add(new RowDefinition { Height = new GridLength(1, GridUnitType.Star) });
            TextBlock detailTitle = new TextBlock { Text = "当前信号配置", FontSize = 16, FontWeight = FontWeights.SemiBold, Foreground = Text(37, 49, 67), VerticalAlignment = VerticalAlignment.Center }; _details.Children.Add(detailTitle);
            Border signalHeader = new Border { Background = new SolidColorBrush(Color.FromRgb(240, 246, 254)), BorderBrush = new SolidColorBrush(Color.FromRgb(199, 218, 242)), BorderThickness = new Thickness(1), CornerRadius = new CornerRadius(4), Padding = new Thickness(12, 7, 12, 7) }; TextBlock signalName = new TextBlock { FontWeight = FontWeights.SemiBold, FontSize = 14, Foreground = Text(37, 49, 67) }; signalName.SetBinding(TextBlock.TextProperty, new Binding("Name")); signalHeader.Child = signalName; Grid.SetRow(signalHeader, 1); _details.Children.Add(signalHeader);
            _use = new CheckBox { Content = "使用该信号", VerticalAlignment = VerticalAlignment.Center }; _use.SetBinding(ToggleButton.IsCheckedProperty, new Binding("Use") { Mode = BindingMode.TwoWay, UpdateSourceTrigger = UpdateSourceTrigger.PropertyChanged }); Grid.SetRow(_use, 2); _details.Children.Add(_use);
            StackPanel modeHeader = new StackPanel { Orientation = Orientation.Horizontal, VerticalAlignment = VerticalAlignment.Center }; modeHeader.Children.Add(new TextBlock { Text = "结果处理方式", Width = 112, VerticalAlignment = VerticalAlignment.Center, Foreground = Text(37, 49, 67) }); _informationMode = ModeButton("只记录", "只记录信息"); _numericMode = ModeButton("数值范围判断", "数值LIMIT"); _stringMode = ModeButton("字符串判断", "字符串匹配"); modeHeader.Children.Add(_informationMode); modeHeader.Children.Add(_numericMode); modeHeader.Children.Add(_stringMode); Grid.SetRow(modeHeader, 3); _details.Children.Add(modeHeader);
            _numericFields = FourFieldGrid("下限", "LowLimitText", "上限", "HighLimitText", "比较方式", "CompareText", "单位", "UnitText"); Grid.SetRow(_numericFields, 4); _details.Children.Add(_numericFields);
            _stringFields = OneFieldGrid("期望字符串", "ExpectedText"); Grid.SetRow(_stringFields, 4); _details.Children.Add(_stringFields);
            _writeFields = OneFieldGrid("写入值", "ValueText"); Grid.SetRow(_writeFields, 4); _details.Children.Add(_writeFields);
            _needsJudgment = new CheckBox { Content = "需要判断", VerticalAlignment = VerticalAlignment.Center, Margin = new Thickness(0, 8, 0, 0) }; _needsJudgment.Checked += (s, e) => { if (!_updating && Current != null && Current.ResultMode == "只记录信息") Current.ResultMode = "数值LIMIT"; RefreshDetailState(); }; _needsJudgment.Unchecked += (s, e) => { if (!_updating && Current != null) Current.ResultMode = "只记录信息"; RefreshDetailState(); }; Grid.SetRow(_needsJudgment, 5); _details.Children.Add(_needsJudgment);
            TextBlock help = new TextBlock { Text = _writeMode ? "选择需要写入的信号并填写写入值。" : "新选择的信号默认只记录；启用“需要判断”后再配置LIMIT。", Foreground = Text(104, 117, 136), TextWrapping = TextWrapping.Wrap, Margin = new Thickness(0, 12, 0, 0) }; Grid.SetRow(help, 6); _details.Children.Add(help); Grid.SetColumn(_details, 2); body.Children.Add(_details); Grid.SetRow(body, 1); root.Children.Add(body);
            DockPanel footer = new DockPanel { Background = Brushes.White, Margin = new Thickness(0) }; _footerSummary = new TextBlock { Foreground = Text(66, 79, 97), VerticalAlignment = VerticalAlignment.Center, Margin = new Thickness(22, 0, 0, 0) }; footer.Children.Add(_footerSummary); StackPanel buttons = new StackPanel { Orientation = Orientation.Horizontal, HorizontalAlignment = HorizontalAlignment.Right, Margin = new Thickness(0, 14, 18, 14) }; DockPanel.SetDock(buttons, Dock.Right); Button cancel = SecondaryButton("取消"); cancel.Click += (s, e) => DialogResult = false; Button apply = PrimaryButton("应用配置"); apply.Click += Apply; buttons.Children.Add(cancel); buttons.Children.Add(apply); footer.Children.Insert(0, buttons); Grid.SetRow(footer, 2); root.Children.Add(footer); Content = root;
            foreach (LocatorSignalRow row in _rows) row.PropertyChanged += RowPropertyChanged; _signalList.SelectedItem = _rows.FirstOrDefault(value => value.Use && value.NeedsJudgment) ?? _rows.FirstOrDefault(value => value.Use) ?? _rows.FirstOrDefault(); _details.DataContext = Current; RefreshDetailState(); RefreshFooter();
        }

        private LocatorSignalRow Current { get { return _signalList.SelectedItem as LocatorSignalRow; } }
        private Button FilterButton(string text) { Button button = SecondaryButton(text); button.Margin = new Thickness(0); button.Click += (s, e) => { _filterMode = text; _view.Refresh(); }; return button; }
        private bool FilterSignal(object value) { LocatorSignalRow row = value as LocatorSignalRow; if (row == null) return false; string search = _search.Text == "搜索信号名称" ? string.Empty : (_search.Text ?? string.Empty).Trim(); bool matches = search.Length == 0 || (row.Name + " " + row.OffsetText + " " + row.DataType).IndexOf(search, StringComparison.OrdinalIgnoreCase) >= 0; return matches && (_filterMode == "全部" || _filterMode == "已选" && row.Use || _filterMode == "有判断" && row.Use && row.NeedsJudgment); }
        private void RowPropertyChanged(object sender, PropertyChangedEventArgs e) { LocatorSignalRow row = sender as LocatorSignalRow; if (_singleMode && e.PropertyName == "Use" && row != null && row.Use) { foreach (LocatorSignalRow other in _rows.Where(value => value != row && value.Use)) other.Use = false; } RefreshFooter(); if (e.PropertyName == "ResultMode") RefreshDetailState(); if (_filterMode != "全部") _view.Refresh(); }
        private void SignalSelectionChanged(object sender, SelectionChangedEventArgs e) { if (_details == null) return; _details.DataContext = Current; RefreshDetailState(); }
        private void RefreshDetailState() { LocatorSignalRow row = Current; bool has = row != null; _details.IsEnabled = has; _updating = true; _needsJudgment.IsChecked = has && row.NeedsJudgment; _informationMode.IsChecked = has && row.ResultMode == "只记录信息"; _numericMode.IsChecked = has && row.ResultMode == "数值LIMIT"; _stringMode.IsChecked = has && row.ResultMode == "字符串匹配"; _updating = false; _numericFields.Visibility = !_writeMode && has && row.ResultMode == "数值LIMIT" ? Visibility.Visible : Visibility.Collapsed; _stringFields.Visibility = !_writeMode && has && row.ResultMode == "字符串匹配" ? Visibility.Visible : Visibility.Collapsed; _writeFields.Visibility = _writeMode && has ? Visibility.Visible : Visibility.Collapsed; _needsJudgment.Visibility = _writeMode ? Visibility.Collapsed : Visibility.Visible; }
        private void RefreshFooter() { int selected = _rows.Count(value => value.Use), judged = _rows.Count(value => value.Use && value.NeedsJudgment); _footerSummary.Text = "已选 " + selected + " 项  ·  " + judged + " 项判断"; }
        private RadioButton ModeButton(string text, string mode) { RadioButton radio = new RadioButton { Content = text, GroupName = "ResultMode", Padding = new Thickness(10, 6, 10, 6), Margin = new Thickness(0, 0, 6, 0), VerticalAlignment = VerticalAlignment.Center }; radio.Checked += (s, e) => { if (!_updating && Current != null) { Current.ResultMode = mode; RefreshDetailState(); } }; return radio; }
        private void Apply(object sender, RoutedEventArgs e) { List<LocatorSignalRow> selected = _rows.Where(value => value.Use).ToList(); if (selected.Count == 0) { MessageBox.Show(this, "请至少选择一个信号。", "信号与判定配置", MessageBoxButton.OK, MessageBoxImage.Information); return; } if (_singleMode && selected.Count != 1) { MessageBox.Show(this, "单信号操作只能选择一个信号。", "信号与判定配置", MessageBoxButton.OK, MessageBoxImage.Information); return; } if (_writeMode && selected.Any(value => string.IsNullOrWhiteSpace(value.ValueText))) { MessageBox.Show(this, "已选择的写入信号必须填写写入值。", "信号与判定配置", MessageBoxButton.OK, MessageBoxImage.Information); return; } foreach (LocatorSignalRow edit in _rows) { LocatorSignalRow original = _sourceRows.FirstOrDefault(value => ReferenceEquals(value.Signal, edit.Signal) || value.Offset == edit.Offset && value.Name == edit.Name); if (original != null) original.CopyConfigurationFrom(edit); } DialogResult = true; }
        private static DataTemplate SignalTemplate() { FrameworkElementFactory row = new FrameworkElementFactory(typeof(DockPanel)); row.SetValue(DockPanel.LastChildFillProperty, true); FrameworkElementFactory check = new FrameworkElementFactory(typeof(CheckBox)); check.SetBinding(ToggleButton.IsCheckedProperty, new Binding("Use") { Mode = BindingMode.TwoWay, UpdateSourceTrigger = UpdateSourceTrigger.PropertyChanged }); check.SetValue(DockPanel.DockProperty, Dock.Left); check.SetValue(FrameworkElement.MarginProperty, new Thickness(10, 8, 10, 8)); check.SetValue(FrameworkElement.VerticalAlignmentProperty, VerticalAlignment.Center); row.AppendChild(check); FrameworkElementFactory stack = new FrameworkElementFactory(typeof(StackPanel)); stack.SetValue(FrameworkElement.MarginProperty, new Thickness(0, 6, 8, 6)); FrameworkElementFactory name = new FrameworkElementFactory(typeof(TextBlock)); name.SetBinding(TextBlock.TextProperty, new Binding("Name")); name.SetValue(TextBlock.FontWeightProperty, FontWeights.SemiBold); name.SetValue(TextBlock.ForegroundProperty, Text(37, 49, 67)); stack.AppendChild(name); FrameworkElementFactory meta = new FrameworkElementFactory(typeof(TextBlock)); MultiBinding binding = new MultiBinding { StringFormat = "{0}  ·  {1}" }; binding.Bindings.Add(new Binding("OffsetText")); binding.Bindings.Add(new Binding("DataType")); meta.SetBinding(TextBlock.TextProperty, binding); meta.SetValue(TextBlock.FontSizeProperty, 11d); meta.SetValue(TextBlock.ForegroundProperty, Text(110, 123, 142)); stack.AppendChild(meta); row.AppendChild(stack); return new DataTemplate { VisualTree = row }; }
        private static Grid FourFieldGrid(string l1, string p1, string l2, string p2, string l3, string p3, string l4, string p4) { Grid grid = new Grid(); for (int i = 0; i < 4; i++) grid.ColumnDefinitions.Add(new ColumnDefinition { Width = new GridLength(1, GridUnitType.Star) }); AddField(grid, l1, p1, 0); AddField(grid, l2, p2, 1); AddField(grid, l3, p3, 2); AddField(grid, l4, p4, 3); return grid; }
        private static Grid OneFieldGrid(string label, string property) { Grid grid = new Grid(); grid.ColumnDefinitions.Add(new ColumnDefinition { Width = new GridLength(160) }); grid.ColumnDefinitions.Add(new ColumnDefinition { Width = new GridLength(340) }); TextBlock text = new TextBlock { Text = label, VerticalAlignment = VerticalAlignment.Center, Foreground = Text(37, 49, 67) }; grid.Children.Add(text); TextBox box = new TextBox { Height = 32, Padding = new Thickness(8, 5, 8, 5), VerticalContentAlignment = VerticalAlignment.Center }; box.SetBinding(TextBox.TextProperty, new Binding(property) { Mode = BindingMode.TwoWay, UpdateSourceTrigger = UpdateSourceTrigger.PropertyChanged }); Grid.SetColumn(box, 1); grid.Children.Add(box); return grid; }
        private static void AddField(Grid grid, string label, string property, int column) { StackPanel panel = new StackPanel { Margin = new Thickness(0, 0, 12, 0) }; panel.Children.Add(new TextBlock { Text = label, Foreground = Text(65, 78, 96), Margin = new Thickness(0, 0, 0, 5) }); Control editor; if (property == "CompareText") { ComboBox combo = new ComboBox { Height = 32, ItemsSource = new[] { "GELE", "GE", "GT", "LE", "LT", "EQ", "NE" } }; combo.SetBinding(Selector.SelectedItemProperty, new Binding(property) { Mode = BindingMode.TwoWay, UpdateSourceTrigger = UpdateSourceTrigger.PropertyChanged }); editor = combo; } else { TextBox box = new TextBox { Height = 32, Padding = new Thickness(8, 5, 8, 5) }; box.SetBinding(TextBox.TextProperty, new Binding(property) { Mode = BindingMode.TwoWay, UpdateSourceTrigger = UpdateSourceTrigger.PropertyChanged }); editor = box; } panel.Children.Add(editor); Grid.SetColumn(panel, column); grid.Children.Add(panel); }
        private static Button PrimaryButton(string text) { return new Button { Content = text, MinWidth = 116, Height = 34, Padding = new Thickness(16, 5, 16, 5), Margin = new Thickness(8, 0, 0, 0), Background = new SolidColorBrush(Color.FromRgb(24, 112, 224)), Foreground = Brushes.White, BorderBrush = new SolidColorBrush(Color.FromRgb(24, 112, 224)), BorderThickness = new Thickness(1) }; }
        private static Button SecondaryButton(string text) { return new Button { Content = text, MinWidth = 94, Height = 34, Padding = new Thickness(14, 5, 14, 5), Margin = new Thickness(8, 0, 0, 0), Background = Brushes.White, Foreground = Text(52, 67, 88), BorderBrush = Border(), BorderThickness = new Thickness(1) }; }
        private static SolidColorBrush Text(byte r, byte g, byte b) { return new SolidColorBrush(Color.FromRgb(r, g, b)); }
        private static SolidColorBrush Border() { return new SolidColorBrush(Color.FromRgb(211, 221, 234)); }
    }
}
