using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Globalization;
using System.Linq;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Effects;

namespace ManualCanDebug
{
    internal sealed class LocatorSignalConfigurationWindow : Window
    {
        private readonly IList<LocatorSignalRow> _sourceRows;
        private readonly ObservableCollection<LocatorSignalRow> _rows;
        private readonly bool _writeMode;
        private readonly bool _singleMode;
        private readonly ListCollectionView _view;
        private readonly ListBox _signalList;
        private readonly TextBox _search;
        private readonly TextBlock _footerSummary;
        private readonly Grid _details;
        private readonly CheckBox _use;
        private readonly ToggleButton _needsJudgment;
        private readonly ToggleButton _informationMode;
        private readonly ToggleButton _numericMode;
        private readonly ToggleButton _stringMode;
        private ToggleButton _allFilter;
        private ToggleButton _selectedFilter;
        private ToggleButton _judgedFilter;
        private readonly Grid _numericFields;
        private readonly Grid _stringFields;
        private readonly Grid _writeFields;
        private string _filterMode = "全部";
        private bool _updating;

        public LocatorSignalConfigurationWindow(IEnumerable<LocatorSignalRow> rows, string operation, string tableName)
        {
            _sourceRows = (rows ?? Enumerable.Empty<LocatorSignalRow>()).ToList(); _rows = new ObservableCollection<LocatorSignalRow>(_sourceRows.Select(value => value.CloneForEditing())); _writeMode = (operation ?? string.Empty).Contains("写入"); _singleMode = (operation ?? string.Empty).Contains("单信号");
            Title = "信号与判定配置"; Width = 1210; Height = 710; MinWidth = 1210; MinHeight = 710; WindowStartupLocation = WindowStartupLocation.CenterOwner; ResizeMode = ResizeMode.NoResize; WindowStyle = WindowStyle.None; AllowsTransparency = true; Background = Brushes.Transparent; FontFamily = new FontFamily("Microsoft YaHei UI"); FontSize = 13; StudioControlTheme.Apply(Resources);
            Border shell = new Border { Background = Brushes.White, BorderBrush = Border(), BorderThickness = new Thickness(1), CornerRadius = new CornerRadius(8), Effect = new DropShadowEffect { BlurRadius = 18, ShadowDepth = 2, Opacity = 0.2, Color = Colors.SlateGray } };
            Grid root = new Grid(); root.RowDefinitions.Add(new RowDefinition { Height = new GridLength(56) }); root.RowDefinitions.Add(new RowDefinition { Height = new GridLength(1, GridUnitType.Star) }); root.RowDefinitions.Add(new RowDefinition { Height = new GridLength(64) });
            DockPanel header = new DockPanel { Background = Brushes.White, LastChildFill = true }; header.MouseLeftButtonDown += (s, e) => { if (e.ButtonState == MouseButtonState.Pressed) DragMove(); }; Button close = new Button { Content = "×", Width = 48, Height = 40, Margin = new Thickness(0, 7, 7, 7), FontSize = 22, Foreground = Text(92, 105, 123), Background = Brushes.Transparent, BorderThickness = new Thickness(0), Cursor = Cursors.Hand }; close.Click += (s, e) => DialogResult = false; DockPanel.SetDock(close, Dock.Right); header.Children.Add(close); header.Children.Add(new TextBlock { Text = "信号与判定配置", FontSize = 18, FontWeight = FontWeights.SemiBold, Foreground = Text(32, 43, 59), VerticalAlignment = VerticalAlignment.Center, Margin = new Thickness(22, 0, 12, 0) }); root.Children.Add(header);
            Grid body = new Grid { Margin = new Thickness(20, 14, 20, 12), Background = Brushes.White }; body.ColumnDefinitions.Add(new ColumnDefinition { Width = new GridLength(418) }); body.ColumnDefinitions.Add(new ColumnDefinition { Width = new GridLength(1) }); body.ColumnDefinitions.Add(new ColumnDefinition { Width = new GridLength(1, GridUnitType.Star) });
            Grid left = new Grid { Margin = new Thickness(0, 4, 20, 0) }; left.RowDefinitions.Add(new RowDefinition { Height = new GridLength(42) }); left.RowDefinitions.Add(new RowDefinition { Height = new GridLength(42) }); left.RowDefinitions.Add(new RowDefinition { Height = new GridLength(1, GridUnitType.Star) });
            Grid searchHost = new Grid(); _search = new TextBox { Height = 34, Padding = new Thickness(36, 6, 10, 6), Text = "搜索信号名称", Foreground = Text(130, 142, 158), ToolTip = "搜索信号名称、Offset或类型" }; _search.GotKeyboardFocus += (s, e) => { if (_search.Text == "搜索信号名称") { _search.Text = string.Empty; _search.Foreground = Text(37, 49, 67); } }; _search.LostKeyboardFocus += (s, e) => { if (string.IsNullOrWhiteSpace(_search.Text)) { _search.Text = "搜索信号名称"; _search.Foreground = Text(130, 142, 158); } }; _search.TextChanged += (s, e) => _view.Refresh(); searchHost.Children.Add(_search); searchHost.Children.Add(new TextBlock { Text = "\uE721", FontFamily = new FontFamily("Segoe MDL2 Assets"), FontSize = 14, Foreground = Text(104, 117, 136), VerticalAlignment = VerticalAlignment.Center, HorizontalAlignment = HorizontalAlignment.Left, Margin = new Thickness(12, 0, 0, 0), IsHitTestVisible = false }); left.Children.Add(searchHost);
            UniformGrid filters = new UniformGrid { Columns = 3, Margin = new Thickness(0, 6, 0, 5) }; _allFilter = FilterButton("全部"); _selectedFilter = FilterButton("已选"); _judgedFilter = FilterButton("有判断"); filters.Children.Add(_allFilter); filters.Children.Add(_selectedFilter); filters.Children.Add(_judgedFilter); _allFilter.IsChecked = true; Grid.SetRow(filters, 1); left.Children.Add(filters);
            _signalList = new ListBox { BorderBrush = Border(), BorderThickness = new Thickness(1), HorizontalContentAlignment = HorizontalAlignment.Stretch, SelectionMode = SelectionMode.Single, ItemContainerStyle = SignalItemStyle(), Background = Brushes.White }; _signalList.Resources[SystemColors.HighlightBrushKey] = new SolidColorBrush(Color.FromRgb(235, 244, 255)); _signalList.Resources[SystemColors.HighlightTextBrushKey] = Text(37, 49, 67); _signalList.Resources[SystemColors.InactiveSelectionHighlightBrushKey] = new SolidColorBrush(Color.FromRgb(235, 244, 255)); _signalList.Resources[SystemColors.InactiveSelectionHighlightTextBrushKey] = Text(37, 49, 67);
            _view = new ListCollectionView(_rows); _view.Filter = FilterSignal; _signalList.ItemsSource = _view; _signalList.ItemTemplate = SignalTemplate(); _signalList.SelectionChanged += SignalSelectionChanged; Grid.SetRow(_signalList, 2); left.Children.Add(_signalList); body.Children.Add(left);
            Border divider = new Border { Background = Border() }; Grid.SetColumn(divider, 1); body.Children.Add(divider);
            _details = new Grid { Margin = new Thickness(34, 4, 22, 10) }; _details.RowDefinitions.Add(new RowDefinition { Height = new GridLength(52) }); _details.RowDefinitions.Add(new RowDefinition { Height = new GridLength(46) }); _details.RowDefinitions.Add(new RowDefinition { Height = new GridLength(54) }); _details.RowDefinitions.Add(new RowDefinition { Height = new GridLength(100) }); _details.RowDefinitions.Add(new RowDefinition { Height = new GridLength(92) }); _details.RowDefinitions.Add(new RowDefinition { Height = new GridLength(62) }); _details.RowDefinitions.Add(new RowDefinition { Height = new GridLength(1, GridUnitType.Star) });
            TextBlock detailTitle = new TextBlock { Text = "当前信号配置", FontSize = 16, FontWeight = FontWeights.SemiBold, Foreground = Text(37, 49, 67), VerticalAlignment = VerticalAlignment.Center }; _details.Children.Add(detailTitle);
            Border signalHeader = new Border { Background = new SolidColorBrush(Color.FromRgb(240, 246, 254)), BorderBrush = new SolidColorBrush(Color.FromRgb(199, 218, 242)), BorderThickness = new Thickness(1), CornerRadius = new CornerRadius(4), Padding = new Thickness(14, 7, 14, 7) }; DockPanel signalHeaderContent = new DockPanel(); TextBlock signalMeta = new TextBlock { Foreground = Text(105, 118, 137), VerticalAlignment = VerticalAlignment.Center, Margin = new Thickness(18, 0, 0, 0) }; MultiBinding signalMetaBinding = new MultiBinding { StringFormat = "{0}  ·  {1}" }; signalMetaBinding.Bindings.Add(new Binding("OffsetText")); signalMetaBinding.Bindings.Add(new Binding("DataType")); signalMeta.SetBinding(TextBlock.TextProperty, signalMetaBinding); TextBlock signalName = new TextBlock { FontWeight = FontWeights.SemiBold, FontSize = 15, Foreground = Text(37, 49, 67), VerticalAlignment = VerticalAlignment.Center }; signalName.SetBinding(TextBlock.TextProperty, new Binding("Name")); signalHeaderContent.Children.Add(signalName); signalHeaderContent.Children.Add(signalMeta); signalHeader.Child = signalHeaderContent; Grid.SetRow(signalHeader, 1); _details.Children.Add(signalHeader);
            _use = new CheckBox { Content = "使用该信号", VerticalAlignment = VerticalAlignment.Center, Style = BlueCheckStyle() }; _use.SetBinding(ToggleButton.IsCheckedProperty, new Binding("Use") { Mode = BindingMode.TwoWay, UpdateSourceTrigger = UpdateSourceTrigger.PropertyChanged }); Grid.SetRow(_use, 2); _details.Children.Add(_use);
            StackPanel modeHeader = new StackPanel { Orientation = Orientation.Vertical, VerticalAlignment = VerticalAlignment.Center }; modeHeader.Children.Add(new TextBlock { Text = "结果处理方式", VerticalAlignment = VerticalAlignment.Center, Foreground = Text(37, 49, 67), Margin = new Thickness(0, 0, 0, 10) }); UniformGrid modeSegments = new UniformGrid { Columns = 3, Width = 480, HorizontalAlignment = HorizontalAlignment.Left }; _informationMode = ModeButton("只记录", "只记录信息"); _numericMode = ModeButton("数值范围判断", "数值LIMIT"); _stringMode = ModeButton("字符串判断", "字符串匹配"); modeSegments.Children.Add(_informationMode); modeSegments.Children.Add(_numericMode); modeSegments.Children.Add(_stringMode); modeHeader.Children.Add(modeSegments); Grid.SetRow(modeHeader, 3); _details.Children.Add(modeHeader);
            _numericFields = FourFieldGrid("下限", "LowLimitText", "上限", "HighLimitText", "比较方式", "CompareText", "单位", "UnitText"); Grid.SetRow(_numericFields, 4); _details.Children.Add(_numericFields);
            _stringFields = OneFieldGrid("期望字符串", "ExpectedText"); Grid.SetRow(_stringFields, 4); _details.Children.Add(_stringFields);
            _writeFields = OneFieldGrid("写入值", "ValueText"); Grid.SetRow(_writeFields, 4); _details.Children.Add(_writeFields);
            StackPanel judgmentRow = new StackPanel { Orientation = Orientation.Horizontal, VerticalAlignment = VerticalAlignment.Center }; judgmentRow.Children.Add(new TextBlock { Text = "需要判断", VerticalAlignment = VerticalAlignment.Center, Foreground = Text(37, 49, 67), Margin = new Thickness(0, 0, 12, 0) }); _needsJudgment = new ToggleButton { Width = 42, Height = 22, Style = SwitchStyle(), Cursor = Cursors.Hand }; _needsJudgment.Click += (s, e) => { if (_updating || Current == null) return; Current.ResultMode = _needsJudgment.IsChecked == true ? (Current.ResultMode == "字符串匹配" ? "字符串匹配" : "数值LIMIT") : "只记录信息"; RefreshDetailState(); }; judgmentRow.Children.Add(_needsJudgment); Grid.SetRow(judgmentRow, 5); _details.Children.Add(judgmentRow);
            TextBlock help = new TextBlock { Text = _writeMode ? "选择需要写入的信号并填写写入值。" : "新选择的信号默认只记录；启用“需要判断”后再配置LIMIT。", Foreground = Text(104, 117, 136), TextWrapping = TextWrapping.Wrap, Margin = new Thickness(0, 12, 0, 0) }; Grid.SetRow(help, 6); _details.Children.Add(help); Grid.SetColumn(_details, 2); body.Children.Add(_details); Grid.SetRow(body, 1); root.Children.Add(body);
            DockPanel footer = new DockPanel { Background = Brushes.White, Margin = new Thickness(0) }; _footerSummary = new TextBlock { Foreground = Text(66, 79, 97), VerticalAlignment = VerticalAlignment.Center, Margin = new Thickness(22, 0, 0, 0) }; footer.Children.Add(_footerSummary); StackPanel buttons = new StackPanel { Orientation = Orientation.Horizontal, HorizontalAlignment = HorizontalAlignment.Right, Margin = new Thickness(0, 14, 18, 14) }; DockPanel.SetDock(buttons, Dock.Right); Button cancel = SecondaryButton("取消"); cancel.Click += (s, e) => DialogResult = false; Button apply = PrimaryButton("应用配置"); apply.Click += Apply; buttons.Children.Add(cancel); buttons.Children.Add(apply); footer.Children.Insert(0, buttons); Grid.SetRow(footer, 2); root.Children.Add(footer); shell.Child = root; Content = shell;
            foreach (LocatorSignalRow row in _rows) row.PropertyChanged += RowPropertyChanged; _signalList.SelectedItem = _rows.FirstOrDefault(value => value.Use && value.NeedsJudgment) ?? _rows.FirstOrDefault(value => value.Use) ?? _rows.FirstOrDefault(); _details.DataContext = Current; RefreshDetailState(); RefreshFooter();
        }

        private LocatorSignalRow Current { get { return _signalList.SelectedItem as LocatorSignalRow; } }
        private ToggleButton FilterButton(string text) { ToggleButton button = new ToggleButton { Content = text, Height = 34, Style = SegmentStyle(), Margin = new Thickness(0), Cursor = Cursors.Hand }; button.Click += (s, e) => { _filterMode = text; _allFilter.IsChecked = ReferenceEquals(button, _allFilter); _selectedFilter.IsChecked = ReferenceEquals(button, _selectedFilter); _judgedFilter.IsChecked = ReferenceEquals(button, _judgedFilter); _view.Refresh(); }; return button; }
        private bool FilterSignal(object value) { LocatorSignalRow row = value as LocatorSignalRow; if (row == null) return false; string search = _search.Text == "搜索信号名称" ? string.Empty : (_search.Text ?? string.Empty).Trim(); bool matches = search.Length == 0 || (row.Name + " " + row.OffsetText + " " + row.DataType).IndexOf(search, StringComparison.OrdinalIgnoreCase) >= 0; return matches && (_filterMode == "全部" || _filterMode == "已选" && row.Use || _filterMode == "有判断" && row.Use && row.NeedsJudgment); }
        private void RowPropertyChanged(object sender, PropertyChangedEventArgs e) { LocatorSignalRow row = sender as LocatorSignalRow; if (_singleMode && e.PropertyName == "Use" && row != null && row.Use) { foreach (LocatorSignalRow other in _rows.Where(value => value != row && value.Use)) other.Use = false; } RefreshFooter(); if (e.PropertyName == "ResultMode") RefreshDetailState(); if (_filterMode != "全部") _view.Refresh(); }
        private void SignalSelectionChanged(object sender, SelectionChangedEventArgs e) { if (_details == null) return; _details.DataContext = Current; RefreshDetailState(); }
        private void RefreshDetailState() { LocatorSignalRow row = Current; bool has = row != null; _details.IsEnabled = has; _updating = true; _needsJudgment.IsChecked = has && row.NeedsJudgment; _informationMode.IsChecked = has && row.ResultMode == "只记录信息"; _numericMode.IsChecked = has && row.ResultMode == "数值LIMIT"; _stringMode.IsChecked = has && row.ResultMode == "字符串匹配"; _updating = false; _numericFields.Visibility = !_writeMode && has && row.ResultMode == "数值LIMIT" ? Visibility.Visible : Visibility.Collapsed; _stringFields.Visibility = !_writeMode && has && row.ResultMode == "字符串匹配" ? Visibility.Visible : Visibility.Collapsed; _writeFields.Visibility = _writeMode && has ? Visibility.Visible : Visibility.Collapsed; _needsJudgment.Visibility = _writeMode ? Visibility.Collapsed : Visibility.Visible; }
        private void RefreshFooter() { int selected = _rows.Count(value => value.Use), judged = _rows.Count(value => value.Use && value.NeedsJudgment); _footerSummary.Text = "已选 " + selected + " 项  ·  " + judged + " 项判断"; }
        private ToggleButton ModeButton(string text, string mode) { ToggleButton button = new ToggleButton { Content = text, Height = 36, Style = SegmentStyle(), Margin = new Thickness(0), Cursor = Cursors.Hand }; button.Click += (s, e) => { if (!_updating && Current != null) { Current.ResultMode = mode; RefreshDetailState(); } }; return button; }
        private void Apply(object sender, RoutedEventArgs e) { List<LocatorSignalRow> selected = _rows.Where(value => value.Use).ToList(); if (selected.Count == 0) { MessageBox.Show(this, "请至少选择一个信号。", "信号与判定配置", MessageBoxButton.OK, MessageBoxImage.Information); return; } if (_singleMode && selected.Count != 1) { MessageBox.Show(this, "单信号操作只能选择一个信号。", "信号与判定配置", MessageBoxButton.OK, MessageBoxImage.Information); return; } if (_writeMode && selected.Any(value => string.IsNullOrWhiteSpace(value.ValueText))) { MessageBox.Show(this, "已选择的写入信号必须填写写入值。", "信号与判定配置", MessageBoxButton.OK, MessageBoxImage.Information); return; } foreach (LocatorSignalRow edit in _rows) { LocatorSignalRow original = _sourceRows.FirstOrDefault(value => ReferenceEquals(value.Signal, edit.Signal) || value.Offset == edit.Offset && value.Name == edit.Name); if (original != null) original.CopyConfigurationFrom(edit); } DialogResult = true; }
        private static DataTemplate SignalTemplate() { FrameworkElementFactory row = new FrameworkElementFactory(typeof(DockPanel)); row.SetValue(DockPanel.LastChildFillProperty, true); FrameworkElementFactory check = new FrameworkElementFactory(typeof(CheckBox)); check.SetBinding(ToggleButton.IsCheckedProperty, new Binding("Use") { Mode = BindingMode.TwoWay, UpdateSourceTrigger = UpdateSourceTrigger.PropertyChanged }); check.SetValue(FrameworkElement.StyleProperty, BlueCheckStyle()); check.SetValue(DockPanel.DockProperty, Dock.Left); check.SetValue(FrameworkElement.MarginProperty, new Thickness(10, 8, 10, 8)); check.SetValue(FrameworkElement.VerticalAlignmentProperty, VerticalAlignment.Center); row.AppendChild(check); FrameworkElementFactory stack = new FrameworkElementFactory(typeof(StackPanel)); stack.SetValue(FrameworkElement.MarginProperty, new Thickness(0, 6, 8, 6)); FrameworkElementFactory name = new FrameworkElementFactory(typeof(TextBlock)); name.SetBinding(TextBlock.TextProperty, new Binding("Name")); name.SetValue(TextBlock.FontWeightProperty, FontWeights.SemiBold); name.SetValue(TextBlock.ForegroundProperty, Text(37, 49, 67)); stack.AppendChild(name); FrameworkElementFactory meta = new FrameworkElementFactory(typeof(TextBlock)); MultiBinding binding = new MultiBinding { StringFormat = "{0}  ·  {1}" }; binding.Bindings.Add(new Binding("OffsetText")); binding.Bindings.Add(new Binding("DataType")); meta.SetBinding(TextBlock.TextProperty, binding); meta.SetValue(TextBlock.FontSizeProperty, 11d); meta.SetValue(TextBlock.ForegroundProperty, Text(110, 123, 142)); stack.AppendChild(meta); row.AppendChild(stack); return new DataTemplate { VisualTree = row }; }
        private static Style SignalItemStyle() { Style style = new Style(typeof(ListBoxItem)); style.Setters.Add(new Setter(Control.HorizontalContentAlignmentProperty, HorizontalAlignment.Stretch)); style.Setters.Add(new Setter(Control.PaddingProperty, new Thickness(0))); style.Setters.Add(new Setter(Control.MarginProperty, new Thickness(0))); style.Setters.Add(new Setter(Control.BackgroundProperty, Brushes.White)); style.Setters.Add(new Setter(Control.BorderBrushProperty, Brushes.Transparent)); style.Setters.Add(new Setter(Control.BorderThicknessProperty, new Thickness(3, 0, 0, 0))); FrameworkElementFactory border = new FrameworkElementFactory(typeof(System.Windows.Controls.Border)); border.SetBinding(System.Windows.Controls.Border.BackgroundProperty, new Binding("Background") { RelativeSource = new RelativeSource(RelativeSourceMode.TemplatedParent) }); border.SetBinding(System.Windows.Controls.Border.BorderBrushProperty, new Binding("BorderBrush") { RelativeSource = new RelativeSource(RelativeSourceMode.TemplatedParent) }); border.SetBinding(System.Windows.Controls.Border.BorderThicknessProperty, new Binding("BorderThickness") { RelativeSource = new RelativeSource(RelativeSourceMode.TemplatedParent) }); FrameworkElementFactory presenter = new FrameworkElementFactory(typeof(ContentPresenter)); presenter.SetBinding(ContentPresenter.ContentProperty, new Binding("Content") { RelativeSource = new RelativeSource(RelativeSourceMode.TemplatedParent) }); presenter.SetBinding(ContentPresenter.ContentTemplateProperty, new Binding("ContentTemplate") { RelativeSource = new RelativeSource(RelativeSourceMode.TemplatedParent) }); border.AppendChild(presenter); style.Setters.Add(new Setter(Control.TemplateProperty, new ControlTemplate(typeof(ListBoxItem)) { VisualTree = border })); Trigger selected = new Trigger { Property = ListBoxItem.IsSelectedProperty, Value = true }; selected.Setters.Add(new Setter(Control.BackgroundProperty, new SolidColorBrush(Color.FromRgb(235, 244, 255)))); selected.Setters.Add(new Setter(Control.BorderBrushProperty, new SolidColorBrush(Color.FromRgb(24, 112, 224)))); style.Triggers.Add(selected); return style; }
        private static Style BlueCheckStyle() { Style style = new Style(typeof(CheckBox)); FrameworkElementFactory root = new FrameworkElementFactory(typeof(DockPanel)); root.SetValue(DockPanel.LastChildFillProperty, true); FrameworkElementFactory box = new FrameworkElementFactory(typeof(System.Windows.Controls.Border)); box.Name = "CheckBoxSquare"; box.SetValue(DockPanel.DockProperty, Dock.Left); box.SetValue(FrameworkElement.WidthProperty, 16d); box.SetValue(FrameworkElement.HeightProperty, 16d); box.SetValue(FrameworkElement.MarginProperty, new Thickness(0, 0, 8, 0)); box.SetValue(System.Windows.Controls.Border.BorderBrushProperty, new SolidColorBrush(Color.FromRgb(139, 151, 168))); box.SetValue(System.Windows.Controls.Border.BorderThicknessProperty, new Thickness(1)); FrameworkElementFactory mark = new FrameworkElementFactory(typeof(TextBlock)); mark.Name = "CheckMark"; mark.SetValue(TextBlock.TextProperty, "✓"); mark.SetValue(TextBlock.ForegroundProperty, Brushes.White); mark.SetValue(TextBlock.FontSizeProperty, 12d); mark.SetValue(TextBlock.FontWeightProperty, FontWeights.Bold); mark.SetValue(FrameworkElement.HorizontalAlignmentProperty, HorizontalAlignment.Center); mark.SetValue(FrameworkElement.VerticalAlignmentProperty, VerticalAlignment.Center); mark.SetValue(UIElement.VisibilityProperty, Visibility.Collapsed); box.AppendChild(mark); root.AppendChild(box); FrameworkElementFactory content = new FrameworkElementFactory(typeof(ContentPresenter)); content.SetBinding(ContentPresenter.ContentProperty, new Binding("Content") { RelativeSource = new RelativeSource(RelativeSourceMode.TemplatedParent) }); content.SetValue(FrameworkElement.VerticalAlignmentProperty, VerticalAlignment.Center); root.AppendChild(content); ControlTemplate template = new ControlTemplate(typeof(CheckBox)) { VisualTree = root }; Trigger on = new Trigger { Property = ToggleButton.IsCheckedProperty, Value = true }; on.Setters.Add(new Setter(System.Windows.Controls.Border.BackgroundProperty, new SolidColorBrush(Color.FromRgb(24, 112, 224)), "CheckBoxSquare")); on.Setters.Add(new Setter(System.Windows.Controls.Border.BorderBrushProperty, new SolidColorBrush(Color.FromRgb(24, 112, 224)), "CheckBoxSquare")); on.Setters.Add(new Setter(UIElement.VisibilityProperty, Visibility.Visible, "CheckMark")); template.Triggers.Add(on); style.Setters.Add(new Setter(Control.TemplateProperty, template)); return style; }
        private static Style SegmentStyle() { Style style = new Style(typeof(ToggleButton)); style.Setters.Add(new Setter(Control.BackgroundProperty, Brushes.White)); style.Setters.Add(new Setter(Control.ForegroundProperty, Text(52, 67, 88))); style.Setters.Add(new Setter(Control.BorderBrushProperty, Border())); style.Setters.Add(new Setter(Control.BorderThicknessProperty, new Thickness(1))); style.Setters.Add(new Setter(Control.PaddingProperty, new Thickness(12, 6, 12, 6))); FrameworkElementFactory border = new FrameworkElementFactory(typeof(System.Windows.Controls.Border)); border.SetBinding(System.Windows.Controls.Border.BackgroundProperty, new Binding("Background") { RelativeSource = new RelativeSource(RelativeSourceMode.TemplatedParent) }); border.SetBinding(System.Windows.Controls.Border.BorderBrushProperty, new Binding("BorderBrush") { RelativeSource = new RelativeSource(RelativeSourceMode.TemplatedParent) }); border.SetBinding(System.Windows.Controls.Border.BorderThicknessProperty, new Binding("BorderThickness") { RelativeSource = new RelativeSource(RelativeSourceMode.TemplatedParent) }); FrameworkElementFactory content = new FrameworkElementFactory(typeof(ContentPresenter)); content.SetValue(FrameworkElement.HorizontalAlignmentProperty, HorizontalAlignment.Center); content.SetValue(FrameworkElement.VerticalAlignmentProperty, VerticalAlignment.Center); content.SetBinding(ContentPresenter.ContentProperty, new Binding("Content") { RelativeSource = new RelativeSource(RelativeSourceMode.TemplatedParent) }); border.AppendChild(content); style.Setters.Add(new Setter(Control.TemplateProperty, new ControlTemplate(typeof(ToggleButton)) { VisualTree = border })); Trigger checkedTrigger = new Trigger { Property = ToggleButton.IsCheckedProperty, Value = true }; checkedTrigger.Setters.Add(new Setter(Control.BackgroundProperty, new SolidColorBrush(Color.FromRgb(24, 112, 224)))); checkedTrigger.Setters.Add(new Setter(Control.ForegroundProperty, Brushes.White)); checkedTrigger.Setters.Add(new Setter(Control.BorderBrushProperty, new SolidColorBrush(Color.FromRgb(24, 112, 224)))); style.Triggers.Add(checkedTrigger); return style; }
        private static Style SwitchStyle() { Style style = new Style(typeof(ToggleButton)); style.Setters.Add(new Setter(Control.BackgroundProperty, new SolidColorBrush(Color.FromRgb(183, 194, 208)))); FrameworkElementFactory border = new FrameworkElementFactory(typeof(System.Windows.Controls.Border)); border.SetValue(System.Windows.Controls.Border.WidthProperty, 42d); border.SetValue(System.Windows.Controls.Border.HeightProperty, 22d); border.SetValue(System.Windows.Controls.Border.CornerRadiusProperty, new CornerRadius(11)); border.SetBinding(System.Windows.Controls.Border.BackgroundProperty, new Binding("Background") { RelativeSource = new RelativeSource(RelativeSourceMode.TemplatedParent) }); FrameworkElementFactory knob = new FrameworkElementFactory(typeof(System.Windows.Shapes.Ellipse)); knob.Name = "SwitchKnob"; knob.SetValue(FrameworkElement.WidthProperty, 16d); knob.SetValue(FrameworkElement.HeightProperty, 16d); knob.SetValue(System.Windows.Shapes.Shape.FillProperty, Brushes.White); knob.SetValue(FrameworkElement.HorizontalAlignmentProperty, HorizontalAlignment.Left); knob.SetValue(FrameworkElement.MarginProperty, new Thickness(3)); border.AppendChild(knob); ControlTemplate template = new ControlTemplate(typeof(ToggleButton)) { VisualTree = border }; Trigger on = new Trigger { Property = ToggleButton.IsCheckedProperty, Value = true }; on.Setters.Add(new Setter(Control.BackgroundProperty, new SolidColorBrush(Color.FromRgb(24, 112, 224)))); on.Setters.Add(new Setter(FrameworkElement.HorizontalAlignmentProperty, HorizontalAlignment.Right, "SwitchKnob")); template.Triggers.Add(on); style.Setters.Add(new Setter(Control.TemplateProperty, template)); return style; }
        private static Grid FourFieldGrid(string l1, string p1, string l2, string p2, string l3, string p3, string l4, string p4) { Grid grid = new Grid(); for (int i = 0; i < 4; i++) grid.ColumnDefinitions.Add(new ColumnDefinition { Width = new GridLength(1, GridUnitType.Star) }); AddField(grid, l1, p1, 0); AddField(grid, l2, p2, 1); AddField(grid, l3, p3, 2); AddField(grid, l4, p4, 3); return grid; }
        private static Grid OneFieldGrid(string label, string property) { Grid grid = new Grid(); grid.ColumnDefinitions.Add(new ColumnDefinition { Width = new GridLength(160) }); grid.ColumnDefinitions.Add(new ColumnDefinition { Width = new GridLength(340) }); TextBlock text = new TextBlock { Text = label, VerticalAlignment = VerticalAlignment.Center, Foreground = Text(37, 49, 67) }; grid.Children.Add(text); TextBox box = new TextBox { Height = 32, Padding = new Thickness(8, 5, 8, 5), VerticalContentAlignment = VerticalAlignment.Center }; box.SetBinding(TextBox.TextProperty, new Binding(property) { Mode = BindingMode.TwoWay, UpdateSourceTrigger = UpdateSourceTrigger.PropertyChanged }); Grid.SetColumn(box, 1); grid.Children.Add(box); return grid; }
        private static void AddField(Grid grid, string label, string property, int column) { StackPanel panel = new StackPanel { Margin = new Thickness(0, 0, 12, 0) }; panel.Children.Add(new TextBlock { Text = label, Foreground = Text(65, 78, 96), Margin = new Thickness(0, 0, 0, 5) }); Control editor; if (property == "CompareText") { ComboBox combo = new ComboBox { Height = 32, ItemsSource = new[] { "GELE", "GE", "GT", "LE", "LT", "EQ", "NE" } }; combo.SetBinding(Selector.SelectedItemProperty, new Binding(property) { Mode = BindingMode.TwoWay, UpdateSourceTrigger = UpdateSourceTrigger.PropertyChanged }); editor = combo; } else { TextBox box = new TextBox { Height = 32, Padding = new Thickness(8, 5, 8, 5) }; box.SetBinding(TextBox.TextProperty, new Binding(property) { Mode = BindingMode.TwoWay, UpdateSourceTrigger = UpdateSourceTrigger.PropertyChanged }); editor = box; } panel.Children.Add(editor); Grid.SetColumn(panel, column); grid.Children.Add(panel); }
        private static Button PrimaryButton(string text) { return new Button { Content = text, MinWidth = 116, Height = 34, Padding = new Thickness(16, 5, 16, 5), Margin = new Thickness(8, 0, 0, 0), Background = new SolidColorBrush(Color.FromRgb(24, 112, 224)), Foreground = Brushes.White, BorderBrush = new SolidColorBrush(Color.FromRgb(24, 112, 224)), BorderThickness = new Thickness(1) }; }
        private static Button SecondaryButton(string text) { return new Button { Content = text, MinWidth = 94, Height = 34, Padding = new Thickness(14, 5, 14, 5), Margin = new Thickness(8, 0, 0, 0), Background = Brushes.White, Foreground = Text(52, 67, 88), BorderBrush = Border(), BorderThickness = new Thickness(1) }; }
        private static SolidColorBrush Text(byte r, byte g, byte b) { return new SolidColorBrush(Color.FromRgb(r, g, b)); }
        private static SolidColorBrush Border() { return new SolidColorBrush(Color.FromRgb(211, 221, 234)); }
    }
}
