using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Globalization;
using System.Linq;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Media;

namespace ManualCanDebug
{
    internal sealed class RelayIoConfigurationWindow : Window
    {
        private readonly ObservableCollection<RelayIoRow> _rows = new ObservableCollection<RelayIoRow>();
        public string Channels { get; private set; }
        public string Values { get; private set; }

        public RelayIoConfigurationWindow(string device, string channels, string values)
        {
            bool functionBoard = string.Equals(device, "RELAY_FCT", StringComparison.OrdinalIgnoreCase); int count = functionBoard ? 48 : 6; Dictionary<int, string> current = Parse(channels, values); for (int index = 0; index < count; index++) { string value; bool selected = current.TryGetValue(index + 1, out value); _rows.Add(new RelayIoRow(index, selected, value == "1", functionBoard ? FunctionText(index + 1) : LatchText(index + 1))); }
            Title = functionBoard ? "FCT功能板IO设置（48路）" : "高压15选1板原始IO（高级）"; Width = 850; Height = 720; MinWidth = 760; MinHeight = 560; Owner = Application.Current == null ? null : Application.Current.MainWindow; WindowStartupLocation = WindowStartupLocation.CenterOwner; Background = Brushes.White; FontFamily = new FontFamily("Microsoft YaHei UI"); FontSize = 13; StudioControlTheme.Apply(Resources);
            Grid root = new Grid { Margin = new Thickness(18) }; root.RowDefinitions.Add(new RowDefinition { Height = GridLength.Auto }); root.RowDefinitions.Add(new RowDefinition { Height = new GridLength(1, GridUnitType.Star) }); root.RowDefinitions.Add(new RowDefinition { Height = GridLength.Auto });
            DockPanel header = new DockPanel { Margin = new Thickness(0, 0, 0, 10) }; StackPanel tools = new StackPanel { Orientation = Orientation.Horizontal }; DockPanel.SetDock(tools, Dock.Right); Button clear = Button("清空选择"); clear.Click += (s, e) => { foreach (RelayIoRow row in _rows) row.Write = false; }; Button allOff = Button("所选全部置0"); allOff.Click += (s, e) => { foreach (RelayIoRow row in _rows.Where(value => value.Write)) row.State = false; }; tools.Children.Add(clear); tools.Children.Add(allOff); header.Children.Add(tools); header.Children.Add(new TextBlock { Text = functionBoard ? "勾选要写入的IO，状态直接选择0/1。Y00 = OUT1 = 线圈地址0。" : "普通调试只操作A0-A3、E、LE；15选1请使用“安全选择测量通道”。", FontWeight = FontWeights.SemiBold, VerticalAlignment = VerticalAlignment.Center }); root.Children.Add(header);
            DataGrid grid = new DataGrid { ItemsSource = _rows, AutoGenerateColumns = false, CanUserAddRows = false, CanUserDeleteRows = false, RowHeight = 36, ColumnHeaderHeight = 38, GridLinesVisibility = DataGridGridLinesVisibility.Horizontal, HeadersVisibility = DataGridHeadersVisibility.Column, SelectionMode = DataGridSelectionMode.Extended, BorderBrush = new SolidColorBrush(Color.FromRgb(211, 221, 234)), BorderThickness = new Thickness(1) }; grid.Columns.Add(new DataGridCheckBoxColumn { Header = "写入", Binding = new Binding("Write") { Mode = BindingMode.TwoWay, UpdateSourceTrigger = UpdateSourceTrigger.PropertyChanged }, Width = 65 }); grid.Columns.Add(new DataGridTextColumn { Header = "板卡输出", Binding = new Binding("BoardPort"), Width = 100, IsReadOnly = true }); grid.Columns.Add(new DataGridTextColumn { Header = "SEQ端口", Binding = new Binding("SeqPort"), Width = 100, IsReadOnly = true }); grid.Columns.Add(new DataGridTextColumn { Header = "线圈地址", Binding = new Binding("CoilAddress"), Width = 100, IsReadOnly = true }); grid.Columns.Add(new DataGridCheckBoxColumn { Header = "状态 0/1", Binding = new Binding("State") { Mode = BindingMode.TwoWay, UpdateSourceTrigger = UpdateSourceTrigger.PropertyChanged }, Width = 90 }); grid.Columns.Add(new DataGridTextColumn { Header = "功能说明", Binding = new Binding("Function"), Width = new DataGridLength(1, DataGridLengthUnitType.Star), IsReadOnly = true }); Grid.SetRow(grid, 1); root.Children.Add(grid);
            StackPanel buttons = new StackPanel { Orientation = Orientation.Horizontal, HorizontalAlignment = HorizontalAlignment.Right, Margin = new Thickness(0, 12, 0, 0) }; Button cancel = Button("取消"); cancel.Click += (s, e) => DialogResult = false; Button apply = Button("应用IO设置"); apply.Background = new SolidColorBrush(Color.FromRgb(24, 112, 224)); apply.Foreground = Brushes.White; apply.Click += (s, e) => { List<RelayIoRow> selected = _rows.Where(value => value.Write).ToList(); if (selected.Count == 0) { MessageBox.Show(this, "请至少勾选一个需要写入的IO。", "IO设置", MessageBoxButton.OK, MessageBoxImage.Information); return; } Channels = string.Join(",", selected.Select(value => value.SeqPort)); Values = string.Join(",", selected.Select(value => value.State ? "1" : "0")); DialogResult = true; }; buttons.Children.Add(cancel); buttons.Children.Add(apply); Grid.SetRow(buttons, 2); root.Children.Add(buttons); Content = root;
        }

        private static Dictionary<int, string> Parse(string channels, string values) { string[] ports = (channels ?? string.Empty).Split(new[] { ',', ';', '|' }, StringSplitOptions.RemoveEmptyEntries), states = (values ?? string.Empty).Split(new[] { ',', ';', '|' }, StringSplitOptions.RemoveEmptyEntries); Dictionary<int, string> result = new Dictionary<int, string>(); for (int i = 0; i < Math.Min(ports.Length, states.Length); i++) { string text = ports[i].Trim().ToUpperInvariant().Replace("OUT", string.Empty); int port; if (int.TryParse(text, NumberStyles.Integer, CultureInfo.InvariantCulture, out port)) result[port] = states[i].Trim(); } return result; }
        private static string FunctionText(int port) { switch (port) { case 6: return "低压程控电源输出路径"; case 7: return "KL30供电 / 万用表电流模式"; case 8: return "KL30旁路"; case 9: return "KL15正端（未接）"; case 10: return "KL15负端"; case 11: return "OBC低压供电"; case 12: return "OBC-KL15"; case 13: return "OBC-KL15负端"; case 14: return "OBC-KL30"; case 15: return "1MTMP1固定电阻"; case 16: return "1MTMP2固定电阻"; case 17: return "2MTMP1固定电阻"; case 18: return "2MTMP2固定电阻"; case 19: return "EPS_MTMP固定电阻"; case 25: return "CC1到LVDC_KL15"; case 26: return "DI2到LVDC_KL15"; case 27: return "DI3到LVDC_KL15"; case 28: return "ACM_CTL到LVDC_KL15"; case 29: return "EPS_CTL到LVDC_KL15"; case 30: return "KL15A到LVDC_KL15"; case 31: return "Instr_CAN到CAN3"; case 33: return "ACM_MTMP"; case 35: return "KL15B到LVDC_KL15"; case 36: return "HVDC主供电"; case 37: return "HVDC预充电"; case 40: return "HVDC放电"; case 43: return "DCDC反灌电压（未用）"; case 45: return "万用表低压/高压测量切换"; default: return "备用/按IO对照表"; } }
        private static string LatchText(int port) { return port == 1 ? "A0" : port == 2 ? "A1" : port == 3 ? "A2" : port == 4 ? "A3" : port == 5 ? "E 使能" : "LE 锁存"; }
        private static Button Button(string text) { return new Button { Content = text, MinWidth = 96, Height = 32, Margin = new Thickness(5, 0, 0, 0), Padding = new Thickness(12, 4, 12, 4) }; }
    }

    internal sealed class RelayIoRow : System.ComponentModel.INotifyPropertyChanged
    {
        private bool _write, _state; public RelayIoRow(int index, bool write, bool state, string function) { Index = index; _write = write; _state = state; Function = function; } public int Index { get; private set; } public string BoardPort { get { return "Y" + Convert.ToString(Index, 8).PadLeft(2, '0'); } } public string SeqPort { get { return "OUT" + (Index + 1).ToString(CultureInfo.InvariantCulture); } } public string CoilAddress { get { return "0x" + Index.ToString("X4", CultureInfo.InvariantCulture); } } public string Function { get; private set; } public bool Write { get { return _write; } set { _write = value; Raise("Write"); } } public bool State { get { return _state; } set { _state = value; Raise("State"); } } private void Raise(string name) { var handler = PropertyChanged; if (handler != null) handler(this, new System.ComponentModel.PropertyChangedEventArgs(name)); } public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    }
}
