using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Markup;
using System.Windows.Media;

namespace ManualCanDebug
{
    internal static class StudioControlTheme
    {
        public static void Apply(ResourceDictionary resources)
        {
            resources[SystemColors.HighlightBrushKey] = Brush(231, 240, 255);
            resources[SystemColors.HighlightTextBrushKey] = Brush(25, 63, 112);
            resources[SystemColors.InactiveSelectionHighlightBrushKey] = Brush(238, 244, 252);
            resources[SystemColors.InactiveSelectionHighlightTextBrushKey] = Brush(37, 49, 67);
            resources[typeof(ComboBox)] = ComboBoxStyle(); resources[typeof(ComboBoxItem)] = ComboBoxItemStyle(); resources[typeof(ScrollBar)] = ScrollBarStyle(); resources[typeof(DataGrid)] = DataGridStyle(); resources[typeof(DataGridColumnHeader)] = HeaderStyle(); resources[typeof(DataGridRow)] = RowStyle(); resources[typeof(DataGridCell)] = CellStyle(); resources[typeof(ContextMenu)] = ContextMenuStyle(); resources[typeof(MenuItem)] = MenuItemStyle();
        }
        internal static Style ComboBoxStyle()
        {
            Style style = new Style(typeof(ComboBox)); style.Setters.Add(new Setter(Control.BackgroundProperty, Brushes.White)); style.Setters.Add(new Setter(Control.ForegroundProperty, Brush(37, 49, 67))); style.Setters.Add(new Setter(Control.BorderBrushProperty, Brush(205, 216, 231))); style.Setters.Add(new Setter(Control.BorderThicknessProperty, new Thickness(1))); style.Setters.Add(new Setter(Control.PaddingProperty, new Thickness(10, 0, 36, 0))); style.Setters.Add(new Setter(Control.MinHeightProperty, 34d)); style.Setters.Add(new Setter(Control.FontFamilyProperty, new FontFamily("Segoe UI"))); style.Setters.Add(new Setter(Control.FontSizeProperty, 13d)); style.Setters.Add(new Setter(ComboBox.VerticalContentAlignmentProperty, VerticalAlignment.Center)); style.Setters.Add(new Setter(ComboBox.HorizontalContentAlignmentProperty, HorizontalAlignment.Stretch)); style.Setters.Add(new Setter(ComboBox.TemplateProperty, ComboTemplate())); return style;
        }
        private static ControlTemplate ComboTemplate()
        {
            ControlTemplate template = new ControlTemplate(typeof(ComboBox)); FrameworkElementFactory grid = new FrameworkElementFactory(typeof(Grid));
            FrameworkElementFactory border = new FrameworkElementFactory(typeof(Border), "Chrome"); border.SetValue(Border.BackgroundProperty, new TemplateBindingExtension(Control.BackgroundProperty)); border.SetValue(Border.BorderBrushProperty, new TemplateBindingExtension(Control.BorderBrushProperty)); border.SetValue(Border.BorderThicknessProperty, new TemplateBindingExtension(Control.BorderThicknessProperty)); border.SetValue(Border.CornerRadiusProperty, new CornerRadius(3)); grid.AppendChild(border);
            FrameworkElementFactory content = new FrameworkElementFactory(typeof(ContentPresenter)); content.SetValue(ContentPresenter.MarginProperty, new Thickness(10, 0, 35, 0)); content.SetValue(ContentPresenter.VerticalAlignmentProperty, VerticalAlignment.Center); content.SetValue(ContentPresenter.HorizontalAlignmentProperty, HorizontalAlignment.Left); content.SetValue(ContentPresenter.ContentProperty, new TemplateBindingExtension(ComboBox.SelectionBoxItemProperty)); content.SetValue(ContentPresenter.ContentTemplateProperty, new TemplateBindingExtension(ComboBox.SelectionBoxItemTemplateProperty)); content.SetValue(ContentPresenter.ContentStringFormatProperty, new TemplateBindingExtension(ComboBox.SelectionBoxItemStringFormatProperty)); content.SetValue(ContentPresenter.SnapsToDevicePixelsProperty, true); grid.AppendChild(content);
            FrameworkElementFactory toggle = new FrameworkElementFactory(typeof(ToggleButton), "DropDownToggle"); toggle.SetValue(ToggleButton.HorizontalAlignmentProperty, HorizontalAlignment.Stretch); toggle.SetValue(ToggleButton.FocusableProperty, false); toggle.SetValue(ToggleButton.ClickModeProperty, ClickMode.Press); toggle.SetBinding(ToggleButton.IsCheckedProperty, new Binding("IsDropDownOpen") { RelativeSource = new RelativeSource(RelativeSourceMode.TemplatedParent), Mode = BindingMode.TwoWay }); toggle.SetValue(ToggleButton.TemplateProperty, ArrowButtonTemplate()); grid.AppendChild(toggle);
            FrameworkElementFactory popup = new FrameworkElementFactory(typeof(Popup), "PART_Popup"); popup.SetValue(Popup.PlacementProperty, PlacementMode.Bottom); popup.SetValue(Popup.AllowsTransparencyProperty, true); popup.SetValue(Popup.FocusableProperty, false); popup.SetValue(Popup.PopupAnimationProperty, PopupAnimation.Fade); popup.SetBinding(Popup.IsOpenProperty, new Binding("IsDropDownOpen") { RelativeSource = new RelativeSource(RelativeSourceMode.TemplatedParent) }); FrameworkElementFactory popupBorder = new FrameworkElementFactory(typeof(Border)); popupBorder.SetValue(Border.BackgroundProperty, Brushes.White); popupBorder.SetValue(Border.BorderBrushProperty, Brush(199, 211, 227)); popupBorder.SetValue(Border.BorderThicknessProperty, new Thickness(1)); popupBorder.SetValue(Border.CornerRadiusProperty, new CornerRadius(3)); popupBorder.SetValue(Border.PaddingProperty, new Thickness(3)); popupBorder.SetBinding(Border.MinWidthProperty, new Binding("ActualWidth") { RelativeSource = new RelativeSource(RelativeSourceMode.TemplatedParent) }); popupBorder.SetValue(Border.EffectProperty, new System.Windows.Media.Effects.DropShadowEffect { BlurRadius = 12, ShadowDepth = 3, Opacity = 0.18, Color = Colors.SlateGray }); FrameworkElementFactory scroll = new FrameworkElementFactory(typeof(ScrollViewer)); scroll.SetValue(ScrollViewer.CanContentScrollProperty, true); scroll.SetValue(ScrollViewer.MaxHeightProperty, 320d); FrameworkElementFactory presenter = new FrameworkElementFactory(typeof(ItemsPresenter)); scroll.AppendChild(presenter); popupBorder.AppendChild(scroll); popup.AppendChild(popupBorder); grid.AppendChild(popup); template.VisualTree = grid;
            Trigger hover = new Trigger { Property = UIElement.IsMouseOverProperty, Value = true }; hover.Setters.Add(new Setter(Border.BorderBrushProperty, Brush(104, 151, 214), "Chrome")); template.Triggers.Add(hover); Trigger focus = new Trigger { Property = UIElement.IsKeyboardFocusWithinProperty, Value = true }; focus.Setters.Add(new Setter(Border.BorderBrushProperty, Brush(24, 112, 224), "Chrome")); focus.Setters.Add(new Setter(Border.BorderThicknessProperty, new Thickness(1.5), "Chrome")); template.Triggers.Add(focus); Trigger disabled = new Trigger { Property = UIElement.IsEnabledProperty, Value = false }; disabled.Setters.Add(new Setter(UIElement.OpacityProperty, 0.5)); template.Triggers.Add(disabled); return template;
        }
        private static ControlTemplate ArrowButtonTemplate()
        {
            ControlTemplate template = new ControlTemplate(typeof(ToggleButton)); FrameworkElementFactory border = new FrameworkElementFactory(typeof(Border), "ArrowHost"); border.SetValue(Border.BackgroundProperty, Brushes.Transparent); FrameworkElementFactory arrow = new FrameworkElementFactory(typeof(TextBlock), "ArrowGlyph"); arrow.SetValue(TextBlock.TextProperty, "\uE70D"); arrow.SetValue(TextBlock.FontFamilyProperty, new FontFamily("Segoe MDL2 Assets")); arrow.SetValue(TextBlock.FontSizeProperty, 11d); arrow.SetValue(TextBlock.ForegroundProperty, Brush(84, 105, 133)); arrow.SetValue(TextBlock.HorizontalAlignmentProperty, HorizontalAlignment.Right); arrow.SetValue(TextBlock.VerticalAlignmentProperty, VerticalAlignment.Center); arrow.SetValue(TextBlock.MarginProperty, new Thickness(0, 0, 10, 0)); border.AppendChild(arrow); template.VisualTree = border; Trigger hover = new Trigger { Property = UIElement.IsMouseOverProperty, Value = true }; hover.Setters.Add(new Setter(TextBlock.ForegroundProperty, Brush(24, 112, 224), "ArrowGlyph")); template.Triggers.Add(hover); Trigger check = new Trigger { Property = ToggleButton.IsCheckedProperty, Value = true }; check.Setters.Add(new Setter(TextBlock.ForegroundProperty, Brush(24, 112, 224), "ArrowGlyph")); template.Triggers.Add(check); return template;
        }
        private static Style ComboBoxItemStyle() { Style style = new Style(typeof(ComboBoxItem)); style.Setters.Add(new Setter(Control.PaddingProperty, new Thickness(10, 7, 10, 7))); style.Setters.Add(new Setter(Control.MarginProperty, new Thickness(1))); style.Setters.Add(new Setter(Control.HorizontalContentAlignmentProperty, HorizontalAlignment.Stretch)); style.Setters.Add(new Setter(Control.ForegroundProperty, Brush(37, 49, 67))); Trigger hover = new Trigger { Property = ComboBoxItem.IsHighlightedProperty, Value = true }; hover.Setters.Add(new Setter(Control.BackgroundProperty, Brush(239, 246, 255))); hover.Setters.Add(new Setter(Control.ForegroundProperty, Brush(24, 112, 224))); style.Triggers.Add(hover); Trigger selected = new Trigger { Property = ComboBoxItem.IsSelectedProperty, Value = true }; selected.Setters.Add(new Setter(Control.BackgroundProperty, Brush(226, 239, 255))); selected.Setters.Add(new Setter(Control.ForegroundProperty, Brush(15, 92, 194))); selected.Setters.Add(new Setter(Control.FontWeightProperty, FontWeights.SemiBold)); style.Triggers.Add(selected); return style; }
        internal static Style ScrollBarStyle()
        {
            Style style = new Style(typeof(ScrollBar)); style.Setters.Add(new Setter(Control.BackgroundProperty, Brushes.Transparent)); style.Setters.Add(new Setter(ScrollBar.WidthProperty, 11d)); style.Setters.Add(new Setter(ScrollBar.MinWidthProperty, 11d)); style.Setters.Add(new Setter(ScrollBar.TemplateProperty, ScrollBarTemplate())); Trigger horizontal = new Trigger { Property = ScrollBar.OrientationProperty, Value = Orientation.Horizontal }; horizontal.Setters.Add(new Setter(ScrollBar.HeightProperty, 11d)); horizontal.Setters.Add(new Setter(ScrollBar.MinHeightProperty, 11d)); horizontal.Setters.Add(new Setter(ScrollBar.WidthProperty, double.NaN)); horizontal.Setters.Add(new Setter(ScrollBar.MinWidthProperty, 0d)); style.Triggers.Add(horizontal); return style;
        }
        private static ControlTemplate ScrollBarTemplate()
        {
            return (ControlTemplate)XamlReader.Parse(@"<ControlTemplate xmlns='http://schemas.microsoft.com/winfx/2006/xaml/presentation' xmlns:x='http://schemas.microsoft.com/winfx/2006/xaml' TargetType='{x:Type ScrollBar}'><Border Background='#EBF0F7' CornerRadius='5' Margin='2'><Track x:Name='PART_Track' Orientation='{TemplateBinding Orientation}' IsDirectionReversed='True'><Track.DecreaseRepeatButton><RepeatButton x:Name='DecreaseButton' Command='{x:Static ScrollBar.PageUpCommand}' Opacity='0'/></Track.DecreaseRepeatButton><Track.Thumb><Thumb><Thumb.Template><ControlTemplate TargetType='{x:Type Thumb}'><Border Background='#97A6BB' CornerRadius='4' Margin='1'/></ControlTemplate></Thumb.Template></Thumb></Track.Thumb><Track.IncreaseRepeatButton><RepeatButton x:Name='IncreaseButton' Command='{x:Static ScrollBar.PageDownCommand}' Opacity='0'/></Track.IncreaseRepeatButton></Track></Border><ControlTemplate.Triggers><Trigger Property='Orientation' Value='Horizontal'><Setter TargetName='DecreaseButton' Property='Command' Value='{x:Static ScrollBar.PageLeftCommand}'/><Setter TargetName='IncreaseButton' Property='Command' Value='{x:Static ScrollBar.PageRightCommand}'/><Setter TargetName='PART_Track' Property='IsDirectionReversed' Value='False'/></Trigger></ControlTemplate.Triggers></ControlTemplate>");
        }
        private static Style DataGridStyle() { Style style = new Style(typeof(DataGrid)); style.Setters.Add(new Setter(Control.BackgroundProperty, Brushes.White)); style.Setters.Add(new Setter(Control.BorderBrushProperty, Brush(216, 226, 239))); style.Setters.Add(new Setter(Control.BorderThicknessProperty, new Thickness(1))); style.Setters.Add(new Setter(DataGrid.GridLinesVisibilityProperty, DataGridGridLinesVisibility.Horizontal)); style.Setters.Add(new Setter(DataGrid.HorizontalGridLinesBrushProperty, Brush(227, 233, 242))); style.Setters.Add(new Setter(DataGrid.VerticalGridLinesBrushProperty, Brushes.Transparent)); style.Setters.Add(new Setter(DataGrid.HeadersVisibilityProperty, DataGridHeadersVisibility.Column)); style.Setters.Add(new Setter(DataGrid.RowHeaderWidthProperty, 0d)); style.Setters.Add(new Setter(DataGrid.ColumnHeaderHeightProperty, 42d)); style.Setters.Add(new Setter(DataGrid.RowHeightProperty, 46d)); style.Setters.Add(new Setter(DataGrid.AlternationCountProperty, 2)); style.Setters.Add(new Setter(DataGrid.SelectionUnitProperty, DataGridSelectionUnit.FullRow)); style.Setters.Add(new Setter(DataGrid.CanUserAddRowsProperty, false)); style.Setters.Add(new Setter(DataGrid.CanUserResizeRowsProperty, false)); style.Setters.Add(new Setter(DataGrid.EnableRowVirtualizationProperty, true)); style.Setters.Add(new Setter(DataGrid.FontSizeProperty, 13d)); return style; }
        private static Style HeaderStyle() { Style style = new Style(typeof(DataGridColumnHeader)); style.Setters.Add(new Setter(Control.BackgroundProperty, Brush(247, 249, 252))); style.Setters.Add(new Setter(Control.ForegroundProperty, Brush(69, 82, 102))); style.Setters.Add(new Setter(Control.FontWeightProperty, FontWeights.SemiBold)); style.Setters.Add(new Setter(Control.FontSizeProperty, 13d)); style.Setters.Add(new Setter(Control.PaddingProperty, new Thickness(10, 0, 8, 0))); style.Setters.Add(new Setter(Control.BorderBrushProperty, Brush(222, 229, 239))); style.Setters.Add(new Setter(Control.BorderThicknessProperty, new Thickness(0, 0, 1, 1))); style.Setters.Add(new Setter(Control.HorizontalContentAlignmentProperty, HorizontalAlignment.Left)); style.Setters.Add(new Setter(Control.VerticalContentAlignmentProperty, VerticalAlignment.Center)); return style; }
        private static Style RowStyle() { Style style = new Style(typeof(DataGridRow)); style.Setters.Add(new Setter(Control.BackgroundProperty, Brushes.White)); style.Setters.Add(new Setter(Control.ForegroundProperty, Brush(37, 49, 67))); style.Setters.Add(new Setter(Control.BorderThicknessProperty, new Thickness(0))); Trigger alternate = new Trigger { Property = ItemsControl.AlternationIndexProperty, Value = 1 }; alternate.Setters.Add(new Setter(Control.BackgroundProperty, Brush(251, 252, 254))); style.Triggers.Add(alternate); Trigger hover = new Trigger { Property = UIElement.IsMouseOverProperty, Value = true }; hover.Setters.Add(new Setter(Control.BackgroundProperty, Brush(244, 248, 253))); style.Triggers.Add(hover); Trigger selected = new Trigger { Property = DataGridRow.IsSelectedProperty, Value = true }; selected.Setters.Add(new Setter(Control.BackgroundProperty, Brush(231, 240, 255))); selected.Setters.Add(new Setter(Control.ForegroundProperty, Brush(25, 63, 112))); selected.Setters.Add(new Setter(Control.FontWeightProperty, FontWeights.Bold)); style.Triggers.Add(selected); return style; }
        private static Style CellStyle() { Style style = new Style(typeof(DataGridCell)); style.Setters.Add(new Setter(Control.BackgroundProperty, Brushes.Transparent)); style.Setters.Add(new Setter(Control.ForegroundProperty, Brush(37, 49, 67))); style.Setters.Add(new Setter(TextElement.ForegroundProperty, Brush(37, 49, 67))); style.Setters.Add(new Setter(Control.PaddingProperty, new Thickness(10, 0, 8, 0))); style.Setters.Add(new Setter(Control.BorderThicknessProperty, new Thickness(0))); style.Setters.Add(new Setter(Control.VerticalContentAlignmentProperty, VerticalAlignment.Center)); style.Setters.Add(new Setter(Control.FocusVisualStyleProperty, null)); Trigger selected = new Trigger { Property = DataGridCell.IsSelectedProperty, Value = true }; selected.Setters.Add(new Setter(Control.BackgroundProperty, Brushes.Transparent)); selected.Setters.Add(new Setter(Control.ForegroundProperty, Brush(25, 63, 112))); selected.Setters.Add(new Setter(TextElement.ForegroundProperty, Brush(25, 63, 112))); selected.Setters.Add(new Setter(Control.FontWeightProperty, FontWeights.Bold)); selected.Setters.Add(new Setter(TextElement.FontWeightProperty, FontWeights.Bold)); style.Triggers.Add(selected); Trigger focus = new Trigger { Property = DataGridCell.IsKeyboardFocusWithinProperty, Value = true }; focus.Setters.Add(new Setter(Control.ForegroundProperty, Brush(25, 63, 112))); focus.Setters.Add(new Setter(TextElement.ForegroundProperty, Brush(25, 63, 112))); focus.Setters.Add(new Setter(Control.FontWeightProperty, FontWeights.Bold)); focus.Setters.Add(new Setter(TextElement.FontWeightProperty, FontWeights.Bold)); style.Triggers.Add(focus); return style; }
        private static Style ContextMenuStyle() { Style style = new Style(typeof(ContextMenu)); style.Setters.Add(new Setter(Control.BackgroundProperty, Brushes.White)); style.Setters.Add(new Setter(Control.BorderBrushProperty, Brush(199, 211, 227))); style.Setters.Add(new Setter(Control.BorderThicknessProperty, new Thickness(1))); style.Setters.Add(new Setter(Control.PaddingProperty, new Thickness(4))); style.Setters.Add(new Setter(Control.FontFamilyProperty, new FontFamily("Segoe UI"))); style.Setters.Add(new Setter(Control.FontSizeProperty, 13d)); style.Setters.Add(new Setter(ContextMenu.HasDropShadowProperty, true)); return style; }
        private static Style MenuItemStyle() { Style style = new Style(typeof(MenuItem)); style.Setters.Add(new Setter(Control.PaddingProperty, new Thickness(12, 7, 18, 7))); style.Setters.Add(new Setter(Control.ForegroundProperty, Brush(37, 49, 67))); style.Setters.Add(new Setter(Control.BackgroundProperty, Brushes.Transparent)); Trigger hover = new Trigger { Property = MenuItem.IsHighlightedProperty, Value = true }; hover.Setters.Add(new Setter(Control.BackgroundProperty, Brush(235, 243, 254))); hover.Setters.Add(new Setter(Control.ForegroundProperty, Brush(24, 112, 224))); style.Triggers.Add(hover); return style; }
        private static SolidColorBrush Brush(byte r, byte g, byte b) { SolidColorBrush value = new SolidColorBrush(Color.FromRgb(r, g, b)); value.Freeze(); return value; }
    }
}
